In [0]:
import pyspark.pandas as ps
import pandas as pd

In [0]:
df = ps.read_csv("/Volumes/sparkcatalog/raw/source/raw_orders/orders.csv")
df.head()

   order_id customer_id  order_date product_id  quantity  price order_status     shipping_address    city    country payment_method  discount     category sales_rep region   ship_date  delivery_days returned  gender
0      1001        C164  2025-12-04       P101         5  27.50      Pending   418 Main St, City8   City8     Canada    Credit Card     11.81  Electronics      SR01  North  2025-12-15              4      Yes   Other
1      1002        C051  2025-12-23       P141         9  44.26     Returned  211 Main St, City10  City10  Australia    Credit Card     15.18     Clothing      SR14   East  2025-12-19              3      Yes  Female
2      1003        C027  2025-12-03       P124         2  38.45    Cancelled   972 Main St, City2   City5  Australia    Credit Card     14.59         Toys      SR04   West  2025-12-07              9       No   Other
3      1004        C159  2025-12-29       P123        10  22.45      Shipped   150 Main St, City2   City3      India           Cash     19.70     Clothing      SR04   West  2025-12-19              8       No    Male
4      1005        C095  2025-12-12       P113         5  71.36      Shipped   168 Main St, City8  City14      India         PayPal      3.27         Home      SR09  South  2025-12-22              1      Yes    Male

In [0]:
df.dtypes

order_id              int32
customer_id          object
order_date           object
product_id           object
quantity              int32
price               float64
order_status         object
shipping_address     object
city                 object
country              object
payment_method       object
discount            float64
category             object
sales_rep            object
region               object
ship_date            object
delivery_days         int32
returned             object
gender               object
dtype: object

In [0]:
df.describe()

          order_id     quantity        price     discount  delivery_days
count  1000.000000  1000.000000  1000.000000  1000.000000    1000.000000
mean   1500.500000     5.637000    52.363820     9.876440       5.669000
std     288.819436     2.791599    27.811866     5.843736       2.832925
min    1001.000000     1.000000     4.190000     0.010000       1.000000
25%    1250.000000     3.000000    28.130000     4.850000       3.000000
50%    1500.000000     6.000000    51.510000     9.810000       6.000000
75%    1750.000000     8.000000    76.470000    14.890000       8.000000
max    2000.000000    10.000000    99.950000    20.000000      10.000000

In [0]:
df[['order_id','customer_id','price']].head()

   order_id customer_id  price
0      1001        C164  27.50
1      1002        C051  44.26
2      1003        C027  38.45
3      1004        C159  22.45
4      1005        C095  71.36

In [0]:
df['new_col'] = df['price']*10
df.head()

   order_id customer_id  order_date product_id  quantity  price order_status     shipping_address    city    country payment_method  discount     category sales_rep region   ship_date  delivery_days returned  gender  new_col
0      1001        C164  2025-12-04       P101         5  27.50      Pending   418 Main St, City8   City8     Canada    Credit Card     11.81  Electronics      SR01  North  2025-12-15              4      Yes   Other    275.0
1      1002        C051  2025-12-23       P141         9  44.26     Returned  211 Main St, City10  City10  Australia    Credit Card     15.18     Clothing      SR14   East  2025-12-19              3      Yes  Female    442.6
2      1003        C027  2025-12-03       P124         2  38.45    Cancelled   972 Main St, City2   City5  Australia    Credit Card     14.59         Toys      SR04   West  2025-12-07              9       No   Other    384.5
3      1004        C159  2025-12-29       P123        10  22.45      Shipped   150 Main St, City2   City3      India           Cash     19.70     Clothing      SR04   West  2025-12-19              8       No    Male    224.5
4      1005        C095  2025-12-12       P113         5  71.36      Shipped   168 Main St, City8  City14      India         PayPal      3.27         Home      SR09  South  2025-12-22              1      Yes    Male    713.6

In [0]:
df['flag'] = df['price']>1000
df.head()

   order_id customer_id  order_date product_id  quantity  price order_status     shipping_address    city    country payment_method  discount     category sales_rep region   ship_date  delivery_days returned  gender  new_col   flag
0      1001        C164  2025-12-04       P101         5  27.50      Pending   418 Main St, City8   City8     Canada    Credit Card     11.81  Electronics      SR01  North  2025-12-15              4      Yes   Other    275.0  False
1      1002        C051  2025-12-23       P141         9  44.26     Returned  211 Main St, City10  City10  Australia    Credit Card     15.18     Clothing      SR14   East  2025-12-19              3      Yes  Female    442.6  False
2      1003        C027  2025-12-03       P124         2  38.45    Cancelled   972 Main St, City2   City5  Australia    Credit Card     14.59         Toys      SR04   West  2025-12-07              9       No   Other    384.5  False
3      1004        C159  2025-12-29       P123        10  22.45      Shipped   150 Main St, City2   City3      India           Cash     19.70     Clothing      SR04   West  2025-12-19              8       No    Male    224.5  False
4      1005        C095  2025-12-12       P113         5  71.36      Shipped   168 Main St, City8  City14      India         PayPal      3.27         Home      SR09  South  2025-12-22              1      Yes    Male    713.6  False

In [0]:
df[df['price']>10].head()

   order_id customer_id  order_date product_id  quantity  price order_status     shipping_address    city    country payment_method  discount     category sales_rep region   ship_date  delivery_days returned  gender  new_col   flag
0      1001        C164  2025-12-04       P101         5  27.50      Pending   418 Main St, City8   City8     Canada    Credit Card     11.81  Electronics      SR01  North  2025-12-15              4      Yes   Other    275.0  False
1      1002        C051  2025-12-23       P141         9  44.26     Returned  211 Main St, City10  City10  Australia    Credit Card     15.18     Clothing      SR14   East  2025-12-19              3      Yes  Female    442.6  False
2      1003        C027  2025-12-03       P124         2  38.45    Cancelled   972 Main St, City2   City5  Australia    Credit Card     14.59         Toys      SR04   West  2025-12-07              9       No   Other    384.5  False
3      1004        C159  2025-12-29       P123        10  22.45      Shipped   150 Main St, City2   City3      India           Cash     19.70     Clothing      SR04   West  2025-12-19              8       No    Male    224.5  False
4      1005        C095  2025-12-12       P113         5  71.36      Shipped   168 Main St, City8  City14      India         PayPal      3.27         Home      SR09  South  2025-12-22              1      Yes    Male    713.6  False

In [0]:
df.sort_values('price',ascending=False).head()

     order_id customer_id  order_date product_id  quantity  price order_status     shipping_address    city    country payment_method  discount     category sales_rep region   ship_date  delivery_days returned  gender  new_col   flag
110      1111        C023  2025-12-03       P119         7  99.95     Returned   170 Main St, City9   City6  Australia      Gift Card     16.47  Electronics      SR05   East  2025-12-06              8       No   Other    999.5  False
504      1505        C070  2025-12-20       P116         7  99.92      Pending  823 Main St, City17   City9         UK    Credit Card      3.23         Toys      SR19  North  2025-12-21              2       No   Other    999.2  False
57       1058        C186  2025-12-10       P137        10  99.88     Returned   817 Main St, City7  City20     France      Gift Card      6.90         Toys      SR18   West  2025-12-31              6      Yes   Other    998.8  False
505      1506        C032  2025-12-27       P108         9  99.88     Returned  644 Main St, City16  City10     France           Cash     17.68        Books      SR09   West  2025-12-19              4       No  Female    998.8  False
74       1075        C165  2025-12-31       P101         1  99.85     Returned   188 Main St, City8   City7        USA      Gift Card     14.25         Home      SR03  North  2025-12-22             10      Yes    Male    998.5  False

# Pandas UDF

### Series To Series

In [0]:
from pyspark.sql.functions import *
from pyspark.sql.types import *

In [0]:
@pandas_udf("double")
def price_func(col1:pd.Series,col2:pd.Series) -> pd.Series:
    return col1 * col2

In [0]:
# Creating a PySpark Dataframe
df_spark = spark.read.format("csv")\
                .option("header","true")\
                .option("inferSchema","true")\
                .load("/Volumes/sparkcatalog/raw/source/raw_orders/orders.csv")


df_spark = df_spark.withColumn("total_price",price_func('price','quantity'))

display(df_spark)

order_id,customer_id,order_date,product_id,quantity,price,order_status,shipping_address,city,country,payment_method,discount,category,sales_rep,region,ship_date,delivery_days,returned,gender,total_price
1001,C164,2025-12-04,P101,5,27.5,Pending,"418 Main St, City8",City8,Canada,Credit Card,11.81,Electronics,SR01,North,2025-12-15,4,Yes,Other,137.5
1002,C051,2025-12-23,P141,9,44.26,Returned,"211 Main St, City10",City10,Australia,Credit Card,15.18,Clothing,SR14,East,2025-12-19,3,Yes,Female,398.34
1003,C027,2025-12-03,P124,2,38.45,Cancelled,"972 Main St, City2",City5,Australia,Credit Card,14.59,Toys,SR04,West,2025-12-07,9,No,Other,76.9
1004,C159,2025-12-29,P123,10,22.45,Shipped,"150 Main St, City2",City3,India,Cash,19.7,Clothing,SR04,West,2025-12-19,8,No,Male,224.5
1005,C095,2025-12-12,P113,5,71.36,Shipped,"168 Main St, City8",City14,India,PayPal,3.27,Home,SR09,South,2025-12-22,1,Yes,Male,356.8
1006,C081,2025-12-13,P117,2,24.24,Cancelled,"270 Main St, City3",City3,Germany,Gift Card,17.69,Sports,SR15,South,2025-12-18,3,Yes,Other,48.48
1007,C144,2025-12-18,P116,10,45.12,Returned,"314 Main St, City11",City13,India,Gift Card,1.82,Electronics,SR04,South,2025-12-12,7,Yes,Female,451.2
1008,C098,2025-12-20,P129,9,28.13,Shipped,"216 Main St, City1",City18,USA,Cash,15.37,Books,SR04,East,2025-12-29,3,No,Male,253.17
1009,C185,2025-12-29,P146,5,97.29,Pending,"992 Main St, City9",City17,Australia,Cash,16.83,Toys,SR20,South,2025-12-11,6,Yes,Other,486.45000000000005
1010,C200,2025-12-30,P133,1,61.49,Returned,"731 Main St, City1",City10,UK,Cash,4.79,Clothing,SR19,North,2025-12-07,8,Yes,Other,61.49
1011,C197,2025-12-05,P108,8,94.89,Pending,"532 Main St, City8",City19,Australia,Gift Card,19.29,Toys,SR07,East,2025-12-27,6,No,Other,759.12
1012,C116,2025-12-04,P115,4,10.14,Shipped,"211 Main St, City10",City5,India,PayPal,0.14,Sports,SR02,South,2025-12-06,1,No,Male,40.56
1013,C132,2025-12-08,P117,8,24.56,Pending,"822 Main St, City15",City13,France,Gift Card,4.86,Home,SR14,South,2025-12-08,2,No,Female,196.48
1014,C109,2025-12-14,P129,1,68.63,Shipped,"311 Main St, City18",City1,Canada,Cash,16.01,Electronics,SR08,South,2025-12-14,9,No,Male,68.63
1015,C109,2025-12-06,P117,8,27.97,Shipped,"115 Main St, City18",City19,USA,Credit Card,13.04,Toys,SR01,North,2025-12-17,3,No,Female,223.76
1016,C124,2025-12-07,P125,1,19.8,Shipped,"225 Main St, City1",City5,Australia,Gift Card,5.7,Sports,SR18,West,2025-12-11,4,No,Male,19.8
1017,C015,2025-12-19,P147,9,9.84,Cancelled,"765 Main St, City4",City13,France,Gift Card,10.06,Toys,SR06,North,2026-01-03,2,Yes,Male,88.56
1018,C153,2025-12-03,P143,4,42.75,Pending,"580 Main St, City18",City20,USA,Credit Card,8.38,Toys,SR19,East,2025-12-18,4,No,Male,171.0
1019,C068,2025-12-13,P108,5,47.88,Shipped,"108 Main St, City4",City5,France,Credit Card,1.47,Clothing,SR17,East,2025-12-10,6,Yes,Male,239.4
1020,C095,2025-12-10,P110,8,84.03,Cancelled,"378 Main St, City18",City3,France,Credit Card,13.36,Toys,SR10,North,2025-12-10,5,Yes,Male,672.24
1021,C191,2025-12-18,P109,5,31.04,Pending,"452 Main St, City6",City7,India,Cash,10.11,Books,SR02,North,2025-12-29,5,Yes,Male,155.2
1022,C086,2025-12-25,P108,5,19.5,Returned,"724 Main St, City13",City10,Germany,Credit Card,2.24,Sports,SR05,North,2025-12-25,10,Yes,Female,97.5
1023,C033,2025-12-02,P119,6,90.29,Shipped,"251 Main St, City3",City12,Canada,PayPal,13.34,Books,SR18,West,2025-12-11,4,Yes,Male,541.74
1024,C106,2025-12-01,P111,6,79.1,Returned,"852 Main St, City20",City13,Australia,PayPal,5.34,Sports,SR04,West,2025-12-04,8,Yes,Male,474.59999999999997
1025,C118,2025-12-12,P119,4,25.39,Pending,"456 Main St, City1",City14,UK,Credit Card,19.34,Books,SR12,West,2026-01-05,6,Yes,Male,101.56
1026,C067,2025-12-06,P137,5,7.66,Returned,"254 Main St, City20",City3,Australia,Cash,8.73,Toys,SR04,West,2025-12-14,5,Yes,Other,38.3
1027,C112,2025-12-01,P133,9,69.93,Pending,"231 Main St, City15",City18,USA,Cash,12.46,Sports,SR04,East,2026-01-03,5,No,Female,629.3700000000001
1028,C104,2025-12-23,P118,9,16.21,Returned,"224 Main St, City11",City6,Canada,PayPal,12.31,Books,SR13,North,2025-12-21,5,Yes,Female,145.89000000000001
1029,C149,2025-12-20,P141,6,48.63,Returned,"816 Main St, City9",City7,France,Gift Card,15.87,Sports,SR06,North,2025-12-20,9,No,Male,291.78000000000003
1030,C193,2025-12-08,P143,5,25.56,Pending,"546 Main St, City6",City3,USA,PayPal,19.68,Toys,SR03,West,2025-12-28,10,Yes,Other,127.8
1031,C179,2025-12-13,P131,7,27.41,Shipped,"709 Main St, City18",City2,USA,Gift Card,4.38,Sports,SR17,West,2025-12-05,9,Yes,Male,191.87
1032,C117,2025-12-05,P129,9,98.83,Cancelled,"472 Main St, City10",City13,France,Gift Card,16.61,Toys,SR15,South,2026-01-01,8,No,Male,889.47
1033,C164,2025-12-09,P149,9,50.51,Pending,"179 Main St, City12",City7,USA,Cash,4.69,Books,SR11,North,2025-12-10,3,Yes,Female,454.59
1034,C178,2025-12-05,P145,4,10.16,Returned,"685 Main St, City10",City5,Germany,Gift Card,1.25,Home,SR13,North,2025-12-26,8,Yes,Female,40.64
1035,C077,2025-12-25,P124,7,55.66,Pending,"674 Main St, City16",City13,UK,Gift Card,9.71,Home,SR11,West,2025-12-12,8,Yes,Other,389.62
1036,C137,2025-12-01,P125,10,58.17,Shipped,"582 Main St, City15",City10,Germany,PayPal,17.34,Clothing,SR02,East,2025-12-26,6,Yes,Female,581.7
1037,C084,2025-12-11,P148,7,30.7,Returned,"399 Main St, City4",City4,Germany,Credit Card,14.98,Electronics,SR12,South,2025-12-06,1,Yes,Male,214.9
1038,C052,2025-12-27,P101,10,18.62,Pending,"481 Main St, City16",City12,USA,PayPal,9.3,Books,SR12,South,2025-12-09,3,No,Male,186.20000000000002
1039,C149,2025-12-01,P119,10,69.02,Returned,"857 Main St, City6",City18,India,Credit Card,11.84,Sports,SR08,North,2025-12-21,10,Yes,Other,690.1999999999999
1040,C011,2025-12-12,P134,7,67.5,Shipped,"992 Main St, City9",City1,UK,Credit Card,16.99,Home,SR04,West,2025-12-25,8,Yes,Female,472.5
1041,C046,2025-12-24,P133,5,63.12,Returned,"330 Main St, City5",City5,Australia,Cash,6.45,Clothing,SR03,East,2025-12-30,4,No,Other,315.59999999999997
1042,C157,2025-12-22,P124,6,6.75,Cancelled,"947 Main St, City6",City18,India,Cash,15.96,Books,SR09,East,2025-12-02,9,Yes,Male,40.5
1043,C062,2025-12-24,P126,8,57.29,Pending,"658 Main St, City4",City3,Canada,Gift Card,8.96,Electronics,SR03,East,2025-12-16,7,Yes,Female,458.32
1044,C170,2025-12-19,P123,8,57.12,Cancelled,"875 Main St, City2",City19,France,Cash,7.04,Home,SR09,East,2025-12-18,4,Yes,Other,456.96
1045,C050,2025-12-11,P107,9,95.27,Pending,"950 Main St, City7",City1,Canada,Gift Card,5.53,Toys,SR17,East,2025-12-08,4,No,Male,857.43
1046,C093,2025-12-06,P119,1,71.96,Pending,"179 Main St, City12",City4,USA,Cash,13.95,Clothing,SR16,North,2025-12-02,10,No,Female,71.96
1047,C123,2025-12-15,P121,3,96.68,Cancelled,"153 Main St, City18",City4,Australia,Credit Card,8.01,Electronics,SR19,North,2025-12-11,3,No,Male,290.04
1048,C064,2025-12-04,P135,7,62.2,Pending,"805 Main St, City4",City9,Germany,Gift Card,18.17,Books,SR19,West,2025-12-21,10,Yes,Other,435.40000000000003
1049,C190,2025-12-04,P148,4,64.04,Cancelled,"696 Main St, City5",City4,India,PayPal,3.48,Electronics,SR06,North,2025-12-28,8,No,Female,256.16
1050,C009,2025-12-08,P118,5,71.48,Returned,"132 Main St, City19",City7,India,Cash,15.76,Sports,SR19,South,2025-12-29,2,Yes,Other,357.40000000000003
1051,C039,2025-12-30,P117,3,10.85,Pending,"886 Main St, City3",City20,Canada,Cash,8.78,Home,SR10,West,2025-12-19,9,No,Female,32.55
1052,C021,2025-12-20,P102,7,74.51,Cancelled,"712 Main St, City18",City6,India,Credit Card,19.99,Sports,SR09,North,2025-12-13,8,No,Female,521.57
1053,C047,2025-12-19,P127,8,97.02,Returned,"462 Main St, City18",City15,UK,Cash,13.4,Clothing,SR11,West,2026-01-02,5,No,Other,776.16
1054,C010,2025-12-15,P105,6,28.22,Shipped,"477 Main St, City3",City1,Australia,Credit Card,13.15,Toys,SR15,West,2025-12-05,4,No,Other,169.32
1055,C194,2025-12-16,P140,8,76.95,Pending,"553 Main St, City6",City19,India,Cash,8.76,Sports,SR16,North,2025-12-03,10,Yes,Other,615.6
1056,C041,2025-12-10,P135,1,57.01,Shipped,"510 Main St, City3",City4,Germany,Credit Card,12.95,Clothing,SR16,East,2026-01-03,5,No,Female,57.01
1057,C121,2025-12-08,P129,9,17.88,Pending,"837 Main St, City1",City9,Canada,PayPal,17.28,Books,SR14,East,2026-01-03,5,Yes,Female,160.92
1058,C186,2025-12-10,P137,10,99.88,Returned,"817 Main St, City7",City20,France,Gift Card,6.9,Toys,SR18,West,2025-12-31,6,Yes,Other,998.8
1059,C062,2025-12-19,P124,4,86.17,Returned,"150 Main St, City2",City19,Canada,Gift Card,14.1,Home,SR13,South,2026-01-02,1,Yes,Other,344.68
1060,C152,2025-12-11,P106,8,13.56,Returned,"234 Main St, City17",City18,India,Gift Card,17.42,Clothing,SR03,West,2025-12-18,6,No,Other,108.48
1061,C021,2025-12-28,P121,9,40.47,Cancelled,"519 Main St, City16",City18,Australia,Gift Card,17.45,Electronics,SR20,North,2025-12-17,5,Yes,Other,364.23
1062,C024,2025-12-14,P106,2,46.58,Cancelled,"544 Main St, City17",City4,UK,Credit Card,5.87,Books,SR14,South,2025-12-17,9,No,Other,93.16
1063,C175,2025-12-26,P111,3,20.8,Returned,"907 Main St, City10",City9,India,Gift Card,18.26,Clothing,SR08,West,2025-12-18,8,No,Other,62.400000000000006
1064,C003,2025-12-29,P129,5,69.04,Pending,"132 Main St, City19",City13,UK,Cash,12.78,Home,SR09,West,2025-12-21,4,No,Female,345.20000000000005
1065,C028,2025-12-08,P124,10,38.45,Cancelled,"761 Main St, City4",City20,USA,Gift Card,5.49,Toys,SR02,West,2025-12-20,4,No,Male,384.5
1066,C163,2025-12-07,P139,5,69.06,Pending,"519 Main St, City16",City8,Canada,Credit Card,6.18,Home,SR02,East,2025-12-10,2,No,Female,345.3
1067,C192,2025-12-14,P111,4,16.68,Cancelled,"192 Main St, City6",City17,UK,PayPal,5.14,Home,SR10,East,2025-12-09,8,Yes,Male,66.72
1068,C194,2025-12-31,P114,7,96.85,Cancelled,"749 Main St, City19",City3,USA,Cash,10.73,Home,SR12,East,2025-12-26,6,Yes,Other,677.9499999999999
1069,C060,2025-12-16,P101,10,88.88,Cancelled,"378 Main St, City18",City13,Canada,Credit Card,12.71,Home,SR10,West,2025-12-09,3,Yes,Male,888.8
1070,C078,2025-12-16,P107,2,26.53,Pending,"225 Main St, City1",City19,UK,Gift Card,11.75,Sports,SR05,West,2025-12-08,8,No,Female,53.06
1071,C009,2025-12-23,P123,4,46.55,Pending,"314 Main St, City11",City7,Canada,Cash,10.89,Sports,SR12,North,2025-12-27,5,Yes,Male,186.2
1072,C117,2025-12-03,P142,4,65.59,Shipped,"262 Main St, City20",City11,India,PayPal,15.74,Clothing,SR03,South,2025-12-15,4,No,Male,262.36
1073,C153,2025-12-01,P117,3,98.79,Cancelled,"292 Main St, City17",City10,Canada,Credit Card,2.64,Books,SR08,East,2025-12-03,3,No,Male,296.37
1074,C033,2025-12-24,P126,9,14.9,Shipped,"481 Main St, City16",City20,Australia,Cash,10.26,Electronics,SR15,South,2025-12-04,9,No,Female,134.1
1075,C165,2025-12-31,P101,1,99.85,Returned,"188 Main St, City8",City7,USA,Gift Card,14.25,Home,SR03,North,2025-12-22,10,Yes,Male,99.85
1076,C033,2025-12-09,P139,10,56.63,Cancelled,"531 Main St, City6",City20,France,Cash,9.07,Toys,SR14,North,2025-12-09,9,Yes,Female,566.3000000000001
1077,C116,2025-12-29,P114,7,36.53,Returned,"456 Main St, City1",City3,Canada,Credit Card,6.25,Books,SR09,East,2025-12-11,8,Yes,Male,255.71
1078,C022,2025-12-03,P127,2,75.47,Cancelled,"173 Main St, City6",City18,USA,Cash,13.4,Home,SR12,West,2025-12-05,5,No,Female,150.94
1079,C027,2025-12-19,P132,4,18.84,Returned,"510 Main St, City3",City17,UK,Cash,2.3,Books,SR19,South,2025-12-29,9,Yes,Other,75.36
1080,C169,2025-12-27,P144,5,6.77,Cancelled,"761 Main St, City4",City5,UK,Cash,7.02,Clothing,SR05,West,2025-12-06,3,Yes,Male,33.849999999999994
1081,C192,2025-12-17,P113,7,44.29,Cancelled,"237 Main St, City4",City12,UK,Cash,15.54,Toys,SR20,North,2025-12-05,3,Yes,Other,310.03
1082,C013,2025-12-22,P105,5,46.53,Returned,"674 Main St, City16",City11,Germany,Gift Card,5.46,Toys,SR04,East,2025-12-29,2,No,Other,232.65
1083,C174,2025-12-19,P131,9,68.03,Shipped,"952 Main St, City17",City3,France,Credit Card,0.15,Books,SR07,South,2025-12-18,5,No,Male,612.27
1084,C002,2025-12-16,P147,7,20.86,Returned,"211 Main St, City4",City10,India,Cash,1.44,Sports,SR02,West,2025-12-03,8,Yes,Female,146.01999999999998
1085,C148,2025-12-14,P136,7,72.1,Returned,"605 Main St, City1",City4,Germany,Credit Card,19.32,Clothing,SR20,West,2025-12-25,2,No,Male,504.69999999999993
1086,C063,2025-12-14,P137,7,54.29,Returned,"718 Main St, City3",City19,UK,PayPal,6.66,Clothing,SR03,North,2026-01-04,9,Yes,Female,380.03
1087,C090,2025-12-24,P141,3,26.67,Pending,"821 Main St, City3",City11,India,PayPal,15.2,Sports,SR03,South,2026-01-02,8,No,Other,80.01
1088,C145,2025-12-21,P140,10,35.02,Cancelled,"817 Main St, City7",City7,USA,Gift Card,8.84,Books,SR09,North,2025-12-24,9,Yes,Female,350.20000000000005
1089,C119,2025-12-15,P102,1,39.39,Cancelled,"771 Main St, City13",City1,Australia,Credit Card,12.3,Toys,SR13,West,2025-12-04,8,Yes,Female,39.39
1090,C155,2025-12-16,P132,3,95.93,Returned,"786 Main St, City6",City7,Canada,Credit Card,10.09,Clothing,SR02,South,2025-12-30,8,Yes,Female,287.79
1091,C096,2025-12-30,P118,7,43.23,Cancelled,"909 Main St, City20",City16,USA,Cash,1.32,Electronics,SR18,West,2025-12-20,5,Yes,Female,302.60999999999996
1092,C021,2025-12-19,P142,3,92.0,Cancelled,"369 Main St, City20",City10,Canada,Gift Card,2.58,Sports,SR03,East,2025-12-26,6,Yes,Other,276.0
1093,C180,2025-12-27,P147,9,12.96,Returned,"801 Main St, City6",City5,USA,Cash,6.18,Clothing,SR11,West,2025-12-14,4,Yes,Male,116.64000000000001
1094,C020,2025-12-10,P106,9,77.99,Shipped,"696 Main St, City5",City8,Australia,PayPal,11.94,Clothing,SR06,South,2025-12-12,8,Yes,Female,701.91
1095,C094,2025-12-22,P146,4,97.07,Cancelled,"709 Main St, City18",City19,Australia,Gift Card,4.68,Clothing,SR10,West,2025-12-14,6,No,Female,388.28
1096,C197,2025-12-10,P149,7,52.27,Returned,"918 Main St, City1",City11,Australia,PayPal,17.46,Electronics,SR16,East,2025-12-08,9,Yes,Female,365.89000000000004
1097,C022,2025-12-25,P110,5,47.12,Pending,"702 Main St, City20",City6,India,Gift Card,17.69,Electronics,SR14,North,2025-12-27,9,No,Male,235.6
1098,C099,2025-12-03,P123,4,6.7,Shipped,"129 Main St, City4",City2,UK,PayPal,2.75,Books,SR16,South,2026-01-01,8,Yes,Male,26.8
1099,C005,2025-12-09,P113,3,56.68,Returned,"280 Main St, City6",City20,UK,PayPal,6.02,Electronics,SR08,West,2025-12-31,2,Yes,Female,170.04
1100,C153,2025-12-18,P101,9,59.19,Pending,"605 Main St, City1",City19,USA,Cash,4.81,Home,SR06,North,2026-01-04,6,Yes,Other,532.71
1101,C140,2025-12-17,P132,9,5.94,Returned,"150 Main St, City2",City14,Germany,Cash,5.07,Electronics,SR12,North,2025-12-24,4,Yes,Other,53.46
1102,C189,2025-12-25,P121,3,8.25,Cancelled,"227 Main St, City16",City9,Australia,Gift Card,19.62,Home,SR06,South,2025-12-06,8,Yes,Female,24.75
1103,C052,2025-12-02,P112,1,34.29,Cancelled,"375 Main St, City11",City3,Australia,Gift Card,5.07,Sports,SR07,East,2025-12-24,1,No,Female,34.29
1104,C032,2025-12-26,P123,7,89.38,Returned,"347 Main St, City12",City8,India,Gift Card,13.84,Books,SR17,East,2025-12-07,7,Yes,Female,625.66
1105,C155,2025-12-27,P111,9,32.19,Shipped,"644 Main St, City12",City9,Canada,Cash,6.13,Toys,SR14,South,2025-12-30,6,No,Male,289.71
1106,C187,2025-12-28,P122,10,99.81,Cancelled,"123 Main St, City14",City8,USA,Gift Card,7.27,Sports,SR06,North,2025-12-11,10,No,Male,998.1
1107,C033,2025-12-03,P115,6,38.76,Shipped,"972 Main St, City2",City12,Canada,Gift Card,18.98,Books,SR15,North,2025-12-10,9,No,Female,232.56
1108,C081,2025-12-21,P117,4,96.2,Shipped,"418 Main St, City8",City2,Germany,Gift Card,18.27,Electronics,SR09,East,2025-12-30,4,No,Other,384.8
1109,C126,2025-12-07,P107,3,85.86,Returned,"292 Main St, City17",City11,Germany,Credit Card,16.21,Books,SR12,North,2026-01-05,5,No,Male,257.58
1110,C183,2025-12-23,P144,3,80.18,Pending,"351 Main St, City10",City11,Australia,PayPal,4.73,Home,SR01,East,2025-12-25,8,Yes,Other,240.54000000000002
1111,C023,2025-12-03,P119,7,99.95,Returned,"170 Main St, City9",City6,Australia,Gift Card,16.47,Electronics,SR05,East,2025-12-06,8,No,Other,699.65
1112,C133,2025-12-12,P108,9,65.41,Pending,"155 Main St, City3",City11,Germany,Credit Card,16.63,Toys,SR05,East,2025-12-12,3,No,Other,588.6899999999999
1113,C058,2025-12-12,P133,5,85.2,Cancelled,"989 Main St, City8",City14,France,Cash,2.5,Books,SR20,North,2026-01-03,3,Yes,Male,426.0
1114,C169,2025-12-20,P146,10,36.4,Shipped,"544 Main St, City17",City4,USA,Cash,13.02,Toys,SR14,North,2026-01-02,9,No,Other,364.0
1115,C078,2025-12-16,P115,7,32.54,Shipped,"658 Main St, City4",City20,India,Gift Card,8.31,Home,SR07,East,2025-12-11,6,No,Other,227.78
1116,C089,2025-12-13,P108,6,53.43,Shipped,"815 Main St, City20",City1,Germany,Credit Card,5.35,Clothing,SR05,North,2025-12-05,5,No,Other,320.58
1117,C108,2025-12-08,P110,6,93.63,Cancelled,"512 Main St, City15",City5,India,Gift Card,19.92,Home,SR16,East,2026-01-02,1,Yes,Female,561.78
1118,C130,2025-12-15,P115,4,59.99,Shipped,"262 Main St, City20",City5,Germany,Gift Card,5.71,Electronics,SR04,West,2025-12-10,5,No,Female,239.96
1119,C094,2025-12-02,P125,1,58.74,Pending,"314 Main St, City11",City5,UK,Credit Card,7.73,Home,SR18,East,2025-12-09,3,Yes,Female,58.74
1120,C096,2025-12-26,P121,9,94.13,Pending,"989 Main St, City8",City15,France,Gift Card,10.0,Electronics,SR02,South,2025-12-23,8,No,Male,847.17
1121,C156,2025-12-29,P132,3,35.47,Cancelled,"918 Main St, City1",City18,France,Cash,11.87,Toys,SR17,West,2025-12-21,8,Yes,Female,106.41
1122,C085,2025-12-22,P107,7,60.03,Shipped,"979 Main St, City15",City3,UK,PayPal,14.43,Toys,SR16,South,2026-01-04,10,No,Male,420.21000000000004
1123,C175,2025-12-08,P102,10,95.02,Shipped,"512 Main St, City15",City2,Germany,Cash,8.38,Home,SR07,West,2026-01-03,10,No,Other,950.1999999999999
1124,C187,2025-12-02,P145,3,53.78,Cancelled,"696 Main St, City5",City8,France,Gift Card,6.28,Clothing,SR15,East,2026-01-05,6,No,Other,161.34
1125,C124,2025-12-07,P115,5,57.57,Pending,"372 Main St, City15",City2,UK,PayPal,13.8,Home,SR11,West,2025-12-24,9,No,Female,287.85
1126,C032,2025-12-19,P143,9,40.44,Returned,"254 Main St, City20",City2,Australia,PayPal,5.81,Books,SR03,East,2025-12-30,5,No,Male,363.96
1127,C052,2025-12-27,P134,5,93.56,Cancelled,"754 Main St, City5",City17,France,PayPal,4.85,Sports,SR17,South,2025-12-16,1,Yes,Female,467.8
1128,C085,2025-12-23,P130,2,69.38,Pending,"713 Main St, City5",City19,India,Gift Card,13.06,Home,SR16,South,2025-12-20,6,No,Other,138.76
1129,C016,2025-12-30,P149,2,66.61,Pending,"211 Main St, City4",City3,Canada,Credit Card,18.26,Clothing,SR14,South,2025-12-04,7,No,Male,133.22
1130,C192,2025-12-31,P118,1,4.88,Shipped,"512 Main St, City20",City5,Germany,Gift Card,17.79,Clothing,SR17,West,2025-12-19,4,Yes,Female,4.88
1131,C042,2025-12-24,P129,5,72.98,Shipped,"418 Main St, City8",City8,Australia,Cash,11.36,Clothing,SR06,West,2025-12-29,9,No,Male,364.90000000000003
1132,C103,2025-12-22,P106,3,98.23,Returned,"192 Main St, City5",City5,USA,Cash,7.67,Home,SR09,East,2025-12-21,10,Yes,Female,294.69
1133,C168,2025-12-12,P144,4,9.95,Shipped,"330 Main St, City5",City20,India,Gift Card,13.72,Sports,SR10,North,2025-12-20,6,Yes,Male,39.8
1134,C035,2025-12-16,P109,8,75.77,Cancelled,"190 Main St, City20",City20,France,Gift Card,15.15,Sports,SR07,South,2025-12-07,9,No,Other,606.16
1135,C181,2025-12-12,P104,10,14.76,Pending,"765 Main St, City1",City6,India,PayPal,6.56,Toys,SR15,North,2025-12-15,10,No,Male,147.6
1136,C131,2025-12-15,P103,8,16.66,Returned,"800 Main St, City4",City6,USA,Gift Card,13.46,Books,SR01,West,2025-12-18,1,Yes,Other,133.28
1137,C019,2025-12-02,P127,6,71.23,Shipped,"393 Main St, City15",City9,USA,Cash,8.18,Clothing,SR14,East,2025-12-26,8,No,Female,427.38
1138,C021,2025-12-22,P142,9,16.76,Cancelled,"938 Main St, City19",City3,France,Gift Card,10.58,Sports,SR08,North,2025-12-03,5,No,Other,150.84
1139,C185,2025-12-18,P127,9,40.4,Pending,"569 Main St, City3",City5,UK,PayPal,5.51,Sports,SR04,North,2025-12-28,10,Yes,Male,363.59999999999997
1140,C053,2025-12-03,P106,10,7.21,Shipped,"364 Main St, City11",City3,USA,Gift Card,8.78,Toys,SR07,North,2025-12-10,9,No,Male,72.1
1141,C188,2025-12-19,P120,10,61.39,Cancelled,"885 Main St, City5",City6,India,PayPal,8.27,Books,SR02,South,2025-12-29,9,No,Male,613.9

### Iterator Series To Iterator Series

In [0]:
from typing import Iterator, Tuple

@pandas_udf("double")
def iter_func(col1: Iterator[pd.Series]) -> Iterator[pd.Series]:

    for batch in col1:
        yield batch * 10

In [0]:
df_spark = df_spark.withColumn("iter_price",iter_func('price'))
display(df_spark)

order_id,customer_id,order_date,product_id,quantity,price,order_status,shipping_address,city,country,payment_method,discount,category,sales_rep,region,ship_date,delivery_days,returned,gender,total_price,iter_price
1001,C164,2025-12-04,P101,5,27.5,Pending,"418 Main St, City8",City8,Canada,Credit Card,11.81,Electronics,SR01,North,2025-12-15,4,Yes,Other,137.5,275.0
1002,C051,2025-12-23,P141,9,44.26,Returned,"211 Main St, City10",City10,Australia,Credit Card,15.18,Clothing,SR14,East,2025-12-19,3,Yes,Female,398.34,442.59999999999997
1003,C027,2025-12-03,P124,2,38.45,Cancelled,"972 Main St, City2",City5,Australia,Credit Card,14.59,Toys,SR04,West,2025-12-07,9,No,Other,76.9,384.5
1004,C159,2025-12-29,P123,10,22.45,Shipped,"150 Main St, City2",City3,India,Cash,19.7,Clothing,SR04,West,2025-12-19,8,No,Male,224.5,224.5
1005,C095,2025-12-12,P113,5,71.36,Shipped,"168 Main St, City8",City14,India,PayPal,3.27,Home,SR09,South,2025-12-22,1,Yes,Male,356.8,713.6
1006,C081,2025-12-13,P117,2,24.24,Cancelled,"270 Main St, City3",City3,Germany,Gift Card,17.69,Sports,SR15,South,2025-12-18,3,Yes,Other,48.48,242.39999999999998
1007,C144,2025-12-18,P116,10,45.12,Returned,"314 Main St, City11",City13,India,Gift Card,1.82,Electronics,SR04,South,2025-12-12,7,Yes,Female,451.2,451.2
1008,C098,2025-12-20,P129,9,28.13,Shipped,"216 Main St, City1",City18,USA,Cash,15.37,Books,SR04,East,2025-12-29,3,No,Male,253.17,281.3
1009,C185,2025-12-29,P146,5,97.29,Pending,"992 Main St, City9",City17,Australia,Cash,16.83,Toys,SR20,South,2025-12-11,6,Yes,Other,486.45000000000005,972.9000000000001
1010,C200,2025-12-30,P133,1,61.49,Returned,"731 Main St, City1",City10,UK,Cash,4.79,Clothing,SR19,North,2025-12-07,8,Yes,Other,61.49,614.9
1011,C197,2025-12-05,P108,8,94.89,Pending,"532 Main St, City8",City19,Australia,Gift Card,19.29,Toys,SR07,East,2025-12-27,6,No,Other,759.12,948.9
1012,C116,2025-12-04,P115,4,10.14,Shipped,"211 Main St, City10",City5,India,PayPal,0.14,Sports,SR02,South,2025-12-06,1,No,Male,40.56,101.4
1013,C132,2025-12-08,P117,8,24.56,Pending,"822 Main St, City15",City13,France,Gift Card,4.86,Home,SR14,South,2025-12-08,2,No,Female,196.48,245.6
1014,C109,2025-12-14,P129,1,68.63,Shipped,"311 Main St, City18",City1,Canada,Cash,16.01,Electronics,SR08,South,2025-12-14,9,No,Male,68.63,686.3
1015,C109,2025-12-06,P117,8,27.97,Shipped,"115 Main St, City18",City19,USA,Credit Card,13.04,Toys,SR01,North,2025-12-17,3,No,Female,223.76,279.7
1016,C124,2025-12-07,P125,1,19.8,Shipped,"225 Main St, City1",City5,Australia,Gift Card,5.7,Sports,SR18,West,2025-12-11,4,No,Male,19.8,198.0
1017,C015,2025-12-19,P147,9,9.84,Cancelled,"765 Main St, City4",City13,France,Gift Card,10.06,Toys,SR06,North,2026-01-03,2,Yes,Male,88.56,98.4
1018,C153,2025-12-03,P143,4,42.75,Pending,"580 Main St, City18",City20,USA,Credit Card,8.38,Toys,SR19,East,2025-12-18,4,No,Male,171.0,427.5
1019,C068,2025-12-13,P108,5,47.88,Shipped,"108 Main St, City4",City5,France,Credit Card,1.47,Clothing,SR17,East,2025-12-10,6,Yes,Male,239.4,478.8
1020,C095,2025-12-10,P110,8,84.03,Cancelled,"378 Main St, City18",City3,France,Credit Card,13.36,Toys,SR10,North,2025-12-10,5,Yes,Male,672.24,840.3
1021,C191,2025-12-18,P109,5,31.04,Pending,"452 Main St, City6",City7,India,Cash,10.11,Books,SR02,North,2025-12-29,5,Yes,Male,155.2,310.4
1022,C086,2025-12-25,P108,5,19.5,Returned,"724 Main St, City13",City10,Germany,Credit Card,2.24,Sports,SR05,North,2025-12-25,10,Yes,Female,97.5,195.0
1023,C033,2025-12-02,P119,6,90.29,Shipped,"251 Main St, City3",City12,Canada,PayPal,13.34,Books,SR18,West,2025-12-11,4,Yes,Male,541.74,902.9000000000001
1024,C106,2025-12-01,P111,6,79.1,Returned,"852 Main St, City20",City13,Australia,PayPal,5.34,Sports,SR04,West,2025-12-04,8,Yes,Male,474.59999999999997,791.0
1025,C118,2025-12-12,P119,4,25.39,Pending,"456 Main St, City1",City14,UK,Credit Card,19.34,Books,SR12,West,2026-01-05,6,Yes,Male,101.56,253.9
1026,C067,2025-12-06,P137,5,7.66,Returned,"254 Main St, City20",City3,Australia,Cash,8.73,Toys,SR04,West,2025-12-14,5,Yes,Other,38.3,76.6
1027,C112,2025-12-01,P133,9,69.93,Pending,"231 Main St, City15",City18,USA,Cash,12.46,Sports,SR04,East,2026-01-03,5,No,Female,629.3700000000001,699.3000000000001
1028,C104,2025-12-23,P118,9,16.21,Returned,"224 Main St, City11",City6,Canada,PayPal,12.31,Books,SR13,North,2025-12-21,5,Yes,Female,145.89000000000001,162.10000000000002
1029,C149,2025-12-20,P141,6,48.63,Returned,"816 Main St, City9",City7,France,Gift Card,15.87,Sports,SR06,North,2025-12-20,9,No,Male,291.78000000000003,486.3
1030,C193,2025-12-08,P143,5,25.56,Pending,"546 Main St, City6",City3,USA,PayPal,19.68,Toys,SR03,West,2025-12-28,10,Yes,Other,127.8,255.6
1031,C179,2025-12-13,P131,7,27.41,Shipped,"709 Main St, City18",City2,USA,Gift Card,4.38,Sports,SR17,West,2025-12-05,9,Yes,Male,191.87,274.1
1032,C117,2025-12-05,P129,9,98.83,Cancelled,"472 Main St, City10",City13,France,Gift Card,16.61,Toys,SR15,South,2026-01-01,8,No,Male,889.47,988.3
1033,C164,2025-12-09,P149,9,50.51,Pending,"179 Main St, City12",City7,USA,Cash,4.69,Books,SR11,North,2025-12-10,3,Yes,Female,454.59,505.09999999999997
1034,C178,2025-12-05,P145,4,10.16,Returned,"685 Main St, City10",City5,Germany,Gift Card,1.25,Home,SR13,North,2025-12-26,8,Yes,Female,40.64,101.6
1035,C077,2025-12-25,P124,7,55.66,Pending,"674 Main St, City16",City13,UK,Gift Card,9.71,Home,SR11,West,2025-12-12,8,Yes,Other,389.62,556.5999999999999
1036,C137,2025-12-01,P125,10,58.17,Shipped,"582 Main St, City15",City10,Germany,PayPal,17.34,Clothing,SR02,East,2025-12-26,6,Yes,Female,581.7,581.7
1037,C084,2025-12-11,P148,7,30.7,Returned,"399 Main St, City4",City4,Germany,Credit Card,14.98,Electronics,SR12,South,2025-12-06,1,Yes,Male,214.9,307.0
1038,C052,2025-12-27,P101,10,18.62,Pending,"481 Main St, City16",City12,USA,PayPal,9.3,Books,SR12,South,2025-12-09,3,No,Male,186.20000000000002,186.20000000000002
1039,C149,2025-12-01,P119,10,69.02,Returned,"857 Main St, City6",City18,India,Credit Card,11.84,Sports,SR08,North,2025-12-21,10,Yes,Other,690.1999999999999,690.1999999999999
1040,C011,2025-12-12,P134,7,67.5,Shipped,"992 Main St, City9",City1,UK,Credit Card,16.99,Home,SR04,West,2025-12-25,8,Yes,Female,472.5,675.0
1041,C046,2025-12-24,P133,5,63.12,Returned,"330 Main St, City5",City5,Australia,Cash,6.45,Clothing,SR03,East,2025-12-30,4,No,Other,315.59999999999997,631.1999999999999
1042,C157,2025-12-22,P124,6,6.75,Cancelled,"947 Main St, City6",City18,India,Cash,15.96,Books,SR09,East,2025-12-02,9,Yes,Male,40.5,67.5
1043,C062,2025-12-24,P126,8,57.29,Pending,"658 Main St, City4",City3,Canada,Gift Card,8.96,Electronics,SR03,East,2025-12-16,7,Yes,Female,458.32,572.9
1044,C170,2025-12-19,P123,8,57.12,Cancelled,"875 Main St, City2",City19,France,Cash,7.04,Home,SR09,East,2025-12-18,4,Yes,Other,456.96,571.1999999999999
1045,C050,2025-12-11,P107,9,95.27,Pending,"950 Main St, City7",City1,Canada,Gift Card,5.53,Toys,SR17,East,2025-12-08,4,No,Male,857.43,952.6999999999999
1046,C093,2025-12-06,P119,1,71.96,Pending,"179 Main St, City12",City4,USA,Cash,13.95,Clothing,SR16,North,2025-12-02,10,No,Female,71.96,719.5999999999999
1047,C123,2025-12-15,P121,3,96.68,Cancelled,"153 Main St, City18",City4,Australia,Credit Card,8.01,Electronics,SR19,North,2025-12-11,3,No,Male,290.04,966.8000000000001
1048,C064,2025-12-04,P135,7,62.2,Pending,"805 Main St, City4",City9,Germany,Gift Card,18.17,Books,SR19,West,2025-12-21,10,Yes,Other,435.40000000000003,622.0
1049,C190,2025-12-04,P148,4,64.04,Cancelled,"696 Main St, City5",City4,India,PayPal,3.48,Electronics,SR06,North,2025-12-28,8,No,Female,256.16,640.4000000000001
1050,C009,2025-12-08,P118,5,71.48,Returned,"132 Main St, City19",City7,India,Cash,15.76,Sports,SR19,South,2025-12-29,2,Yes,Other,357.40000000000003,714.8000000000001
1051,C039,2025-12-30,P117,3,10.85,Pending,"886 Main St, City3",City20,Canada,Cash,8.78,Home,SR10,West,2025-12-19,9,No,Female,32.55,108.5
1052,C021,2025-12-20,P102,7,74.51,Cancelled,"712 Main St, City18",City6,India,Credit Card,19.99,Sports,SR09,North,2025-12-13,8,No,Female,521.57,745.1
1053,C047,2025-12-19,P127,8,97.02,Returned,"462 Main St, City18",City15,UK,Cash,13.4,Clothing,SR11,West,2026-01-02,5,No,Other,776.16,970.1999999999999
1054,C010,2025-12-15,P105,6,28.22,Shipped,"477 Main St, City3",City1,Australia,Credit Card,13.15,Toys,SR15,West,2025-12-05,4,No,Other,169.32,282.2
1055,C194,2025-12-16,P140,8,76.95,Pending,"553 Main St, City6",City19,India,Cash,8.76,Sports,SR16,North,2025-12-03,10,Yes,Other,615.6,769.5
1056,C041,2025-12-10,P135,1,57.01,Shipped,"510 Main St, City3",City4,Germany,Credit Card,12.95,Clothing,SR16,East,2026-01-03,5,No,Female,57.01,570.1
1057,C121,2025-12-08,P129,9,17.88,Pending,"837 Main St, City1",City9,Canada,PayPal,17.28,Books,SR14,East,2026-01-03,5,Yes,Female,160.92,178.79999999999998
1058,C186,2025-12-10,P137,10,99.88,Returned,"817 Main St, City7",City20,France,Gift Card,6.9,Toys,SR18,West,2025-12-31,6,Yes,Other,998.8,998.8
1059,C062,2025-12-19,P124,4,86.17,Returned,"150 Main St, City2",City19,Canada,Gift Card,14.1,Home,SR13,South,2026-01-02,1,Yes,Other,344.68,861.7
1060,C152,2025-12-11,P106,8,13.56,Returned,"234 Main St, City17",City18,India,Gift Card,17.42,Clothing,SR03,West,2025-12-18,6,No,Other,108.48,135.6
1061,C021,2025-12-28,P121,9,40.47,Cancelled,"519 Main St, City16",City18,Australia,Gift Card,17.45,Electronics,SR20,North,2025-12-17,5,Yes,Other,364.23,404.7
1062,C024,2025-12-14,P106,2,46.58,Cancelled,"544 Main St, City17",City4,UK,Credit Card,5.87,Books,SR14,South,2025-12-17,9,No,Other,93.16,465.79999999999995
1063,C175,2025-12-26,P111,3,20.8,Returned,"907 Main St, City10",City9,India,Gift Card,18.26,Clothing,SR08,West,2025-12-18,8,No,Other,62.400000000000006,208.0
1064,C003,2025-12-29,P129,5,69.04,Pending,"132 Main St, City19",City13,UK,Cash,12.78,Home,SR09,West,2025-12-21,4,No,Female,345.20000000000005,690.4000000000001
1065,C028,2025-12-08,P124,10,38.45,Cancelled,"761 Main St, City4",City20,USA,Gift Card,5.49,Toys,SR02,West,2025-12-20,4,No,Male,384.5,384.5
1066,C163,2025-12-07,P139,5,69.06,Pending,"519 Main St, City16",City8,Canada,Credit Card,6.18,Home,SR02,East,2025-12-10,2,No,Female,345.3,690.6
1067,C192,2025-12-14,P111,4,16.68,Cancelled,"192 Main St, City6",City17,UK,PayPal,5.14,Home,SR10,East,2025-12-09,8,Yes,Male,66.72,166.8
1068,C194,2025-12-31,P114,7,96.85,Cancelled,"749 Main St, City19",City3,USA,Cash,10.73,Home,SR12,East,2025-12-26,6,Yes,Other,677.9499999999999,968.5
1069,C060,2025-12-16,P101,10,88.88,Cancelled,"378 Main St, City18",City13,Canada,Credit Card,12.71,Home,SR10,West,2025-12-09,3,Yes,Male,888.8,888.8
1070,C078,2025-12-16,P107,2,26.53,Pending,"225 Main St, City1",City19,UK,Gift Card,11.75,Sports,SR05,West,2025-12-08,8,No,Female,53.06,265.3
1071,C009,2025-12-23,P123,4,46.55,Pending,"314 Main St, City11",City7,Canada,Cash,10.89,Sports,SR12,North,2025-12-27,5,Yes,Male,186.2,465.5
1072,C117,2025-12-03,P142,4,65.59,Shipped,"262 Main St, City20",City11,India,PayPal,15.74,Clothing,SR03,South,2025-12-15,4,No,Male,262.36,655.9000000000001
1073,C153,2025-12-01,P117,3,98.79,Cancelled,"292 Main St, City17",City10,Canada,Credit Card,2.64,Books,SR08,East,2025-12-03,3,No,Male,296.37,987.9000000000001
1074,C033,2025-12-24,P126,9,14.9,Shipped,"481 Main St, City16",City20,Australia,Cash,10.26,Electronics,SR15,South,2025-12-04,9,No,Female,134.1,149.0
1075,C165,2025-12-31,P101,1,99.85,Returned,"188 Main St, City8",City7,USA,Gift Card,14.25,Home,SR03,North,2025-12-22,10,Yes,Male,99.85,998.5
1076,C033,2025-12-09,P139,10,56.63,Cancelled,"531 Main St, City6",City20,France,Cash,9.07,Toys,SR14,North,2025-12-09,9,Yes,Female,566.3000000000001,566.3000000000001
1077,C116,2025-12-29,P114,7,36.53,Returned,"456 Main St, City1",City3,Canada,Credit Card,6.25,Books,SR09,East,2025-12-11,8,Yes,Male,255.71,365.3
1078,C022,2025-12-03,P127,2,75.47,Cancelled,"173 Main St, City6",City18,USA,Cash,13.4,Home,SR12,West,2025-12-05,5,No,Female,150.94,754.7
1079,C027,2025-12-19,P132,4,18.84,Returned,"510 Main St, City3",City17,UK,Cash,2.3,Books,SR19,South,2025-12-29,9,Yes,Other,75.36,188.4
1080,C169,2025-12-27,P144,5,6.77,Cancelled,"761 Main St, City4",City5,UK,Cash,7.02,Clothing,SR05,West,2025-12-06,3,Yes,Male,33.849999999999994,67.69999999999999
1081,C192,2025-12-17,P113,7,44.29,Cancelled,"237 Main St, City4",City12,UK,Cash,15.54,Toys,SR20,North,2025-12-05,3,Yes,Other,310.03,442.9
1082,C013,2025-12-22,P105,5,46.53,Returned,"674 Main St, City16",City11,Germany,Gift Card,5.46,Toys,SR04,East,2025-12-29,2,No,Other,232.65,465.3
1083,C174,2025-12-19,P131,9,68.03,Shipped,"952 Main St, City17",City3,France,Credit Card,0.15,Books,SR07,South,2025-12-18,5,No,Male,612.27,680.3
1084,C002,2025-12-16,P147,7,20.86,Returned,"211 Main St, City4",City10,India,Cash,1.44,Sports,SR02,West,2025-12-03,8,Yes,Female,146.01999999999998,208.6
1085,C148,2025-12-14,P136,7,72.1,Returned,"605 Main St, City1",City4,Germany,Credit Card,19.32,Clothing,SR20,West,2025-12-25,2,No,Male,504.69999999999993,721.0
1086,C063,2025-12-14,P137,7,54.29,Returned,"718 Main St, City3",City19,UK,PayPal,6.66,Clothing,SR03,North,2026-01-04,9,Yes,Female,380.03,542.9
1087,C090,2025-12-24,P141,3,26.67,Pending,"821 Main St, City3",City11,India,PayPal,15.2,Sports,SR03,South,2026-01-02,8,No,Other,80.01,266.70000000000005
1088,C145,2025-12-21,P140,10,35.02,Cancelled,"817 Main St, City7",City7,USA,Gift Card,8.84,Books,SR09,North,2025-12-24,9,Yes,Female,350.20000000000005,350.20000000000005
1089,C119,2025-12-15,P102,1,39.39,Cancelled,"771 Main St, City13",City1,Australia,Credit Card,12.3,Toys,SR13,West,2025-12-04,8,Yes,Female,39.39,393.9
1090,C155,2025-12-16,P132,3,95.93,Returned,"786 Main St, City6",City7,Canada,Credit Card,10.09,Clothing,SR02,South,2025-12-30,8,Yes,Female,287.79,959.3000000000001
1091,C096,2025-12-30,P118,7,43.23,Cancelled,"909 Main St, City20",City16,USA,Cash,1.32,Electronics,SR18,West,2025-12-20,5,Yes,Female,302.60999999999996,432.29999999999995
1092,C021,2025-12-19,P142,3,92.0,Cancelled,"369 Main St, City20",City10,Canada,Gift Card,2.58,Sports,SR03,East,2025-12-26,6,Yes,Other,276.0,920.0
1093,C180,2025-12-27,P147,9,12.96,Returned,"801 Main St, City6",City5,USA,Cash,6.18,Clothing,SR11,West,2025-12-14,4,Yes,Male,116.64000000000001,129.60000000000002
1094,C020,2025-12-10,P106,9,77.99,Shipped,"696 Main St, City5",City8,Australia,PayPal,11.94,Clothing,SR06,South,2025-12-12,8,Yes,Female,701.91,779.9
1095,C094,2025-12-22,P146,4,97.07,Cancelled,"709 Main St, City18",City19,Australia,Gift Card,4.68,Clothing,SR10,West,2025-12-14,6,No,Female,388.28,970.6999999999999
1096,C197,2025-12-10,P149,7,52.27,Returned,"918 Main St, City1",City11,Australia,PayPal,17.46,Electronics,SR16,East,2025-12-08,9,Yes,Female,365.89000000000004,522.7
1097,C022,2025-12-25,P110,5,47.12,Pending,"702 Main St, City20",City6,India,Gift Card,17.69,Electronics,SR14,North,2025-12-27,9,No,Male,235.6,471.2
1098,C099,2025-12-03,P123,4,6.7,Shipped,"129 Main St, City4",City2,UK,PayPal,2.75,Books,SR16,South,2026-01-01,8,Yes,Male,26.8,67.0
1099,C005,2025-12-09,P113,3,56.68,Returned,"280 Main St, City6",City20,UK,PayPal,6.02,Electronics,SR08,West,2025-12-31,2,Yes,Female,170.04,566.8
1100,C153,2025-12-18,P101,9,59.19,Pending,"605 Main St, City1",City19,USA,Cash,4.81,Home,SR06,North,2026-01-04,6,Yes,Other,532.71,591.9
1101,C140,2025-12-17,P132,9,5.94,Returned,"150 Main St, City2",City14,Germany,Cash,5.07,Electronics,SR12,North,2025-12-24,4,Yes,Other,53.46,59.400000000000006
1102,C189,2025-12-25,P121,3,8.25,Cancelled,"227 Main St, City16",City9,Australia,Gift Card,19.62,Home,SR06,South,2025-12-06,8,Yes,Female,24.75,82.5
1103,C052,2025-12-02,P112,1,34.29,Cancelled,"375 Main St, City11",City3,Australia,Gift Card,5.07,Sports,SR07,East,2025-12-24,1,No,Female,34.29,342.9
1104,C032,2025-12-26,P123,7,89.38,Returned,"347 Main St, City12",City8,India,Gift Card,13.84,Books,SR17,East,2025-12-07,7,Yes,Female,625.66,893.8
1105,C155,2025-12-27,P111,9,32.19,Shipped,"644 Main St, City12",City9,Canada,Cash,6.13,Toys,SR14,South,2025-12-30,6,No,Male,289.71,321.9
1106,C187,2025-12-28,P122,10,99.81,Cancelled,"123 Main St, City14",City8,USA,Gift Card,7.27,Sports,SR06,North,2025-12-11,10,No,Male,998.1,998.1
1107,C033,2025-12-03,P115,6,38.76,Shipped,"972 Main St, City2",City12,Canada,Gift Card,18.98,Books,SR15,North,2025-12-10,9,No,Female,232.56,387.59999999999997
1108,C081,2025-12-21,P117,4,96.2,Shipped,"418 Main St, City8",City2,Germany,Gift Card,18.27,Electronics,SR09,East,2025-12-30,4,No,Other,384.8,962.0
1109,C126,2025-12-07,P107,3,85.86,Returned,"292 Main St, City17",City11,Germany,Credit Card,16.21,Books,SR12,North,2026-01-05,5,No,Male,257.58,858.6
1110,C183,2025-12-23,P144,3,80.18,Pending,"351 Main St, City10",City11,Australia,PayPal,4.73,Home,SR01,East,2025-12-25,8,Yes,Other,240.54000000000002,801.8000000000001
1111,C023,2025-12-03,P119,7,99.95,Returned,"170 Main St, City9",City6,Australia,Gift Card,16.47,Electronics,SR05,East,2025-12-06,8,No,Other,699.65,999.5
1112,C133,2025-12-12,P108,9,65.41,Pending,"155 Main St, City3",City11,Germany,Credit Card,16.63,Toys,SR05,East,2025-12-12,3,No,Other,588.6899999999999,654.0999999999999
1113,C058,2025-12-12,P133,5,85.2,Cancelled,"989 Main St, City8",City14,France,Cash,2.5,Books,SR20,North,2026-01-03,3,Yes,Male,426.0,852.0
1114,C169,2025-12-20,P146,10,36.4,Shipped,"544 Main St, City17",City4,USA,Cash,13.02,Toys,SR14,North,2026-01-02,9,No,Other,364.0,364.0
1115,C078,2025-12-16,P115,7,32.54,Shipped,"658 Main St, City4",City20,India,Gift Card,8.31,Home,SR07,East,2025-12-11,6,No,Other,227.78,325.4
1116,C089,2025-12-13,P108,6,53.43,Shipped,"815 Main St, City20",City1,Germany,Credit Card,5.35,Clothing,SR05,North,2025-12-05,5,No,Other,320.58,534.3
1117,C108,2025-12-08,P110,6,93.63,Cancelled,"512 Main St, City15",City5,India,Gift Card,19.92,Home,SR16,East,2026-01-02,1,Yes,Female,561.78,936.3
1118,C130,2025-12-15,P115,4,59.99,Shipped,"262 Main St, City20",City5,Germany,Gift Card,5.71,Electronics,SR04,West,2025-12-10,5,No,Female,239.96,599.9
1119,C094,2025-12-02,P125,1,58.74,Pending,"314 Main St, City11",City5,UK,Credit Card,7.73,Home,SR18,East,2025-12-09,3,Yes,Female,58.74,587.4
1120,C096,2025-12-26,P121,9,94.13,Pending,"989 Main St, City8",City15,France,Gift Card,10.0,Electronics,SR02,South,2025-12-23,8,No,Male,847.17,941.3
1121,C156,2025-12-29,P132,3,35.47,Cancelled,"918 Main St, City1",City18,France,Cash,11.87,Toys,SR17,West,2025-12-21,8,Yes,Female,106.41,354.7
1122,C085,2025-12-22,P107,7,60.03,Shipped,"979 Main St, City15",City3,UK,PayPal,14.43,Toys,SR16,South,2026-01-04,10,No,Male,420.21000000000004,600.3
1123,C175,2025-12-08,P102,10,95.02,Shipped,"512 Main St, City15",City2,Germany,Cash,8.38,Home,SR07,West,2026-01-03,10,No,Other,950.1999999999999,950.1999999999999
1124,C187,2025-12-02,P145,3,53.78,Cancelled,"696 Main St, City5",City8,France,Gift Card,6.28,Clothing,SR15,East,2026-01-05,6,No,Other,161.34,537.8
1125,C124,2025-12-07,P115,5,57.57,Pending,"372 Main St, City15",City2,UK,PayPal,13.8,Home,SR11,West,2025-12-24,9,No,Female,287.85,575.7
1126,C032,2025-12-19,P143,9,40.44,Returned,"254 Main St, City20",City2,Australia,PayPal,5.81,Books,SR03,East,2025-12-30,5,No,Male,363.96,404.4
1127,C052,2025-12-27,P134,5,93.56,Cancelled,"754 Main St, City5",City17,France,PayPal,4.85,Sports,SR17,South,2025-12-16,1,Yes,Female,467.8,935.6
1128,C085,2025-12-23,P130,2,69.38,Pending,"713 Main St, City5",City19,India,Gift Card,13.06,Home,SR16,South,2025-12-20,6,No,Other,138.76,693.8
1129,C016,2025-12-30,P149,2,66.61,Pending,"211 Main St, City4",City3,Canada,Credit Card,18.26,Clothing,SR14,South,2025-12-04,7,No,Male,133.22,666.1
1130,C192,2025-12-31,P118,1,4.88,Shipped,"512 Main St, City20",City5,Germany,Gift Card,17.79,Clothing,SR17,West,2025-12-19,4,Yes,Female,4.88,48.8
1131,C042,2025-12-24,P129,5,72.98,Shipped,"418 Main St, City8",City8,Australia,Cash,11.36,Clothing,SR06,West,2025-12-29,9,No,Male,364.90000000000003,729.8000000000001
1132,C103,2025-12-22,P106,3,98.23,Returned,"192 Main St, City5",City5,USA,Cash,7.67,Home,SR09,East,2025-12-21,10,Yes,Female,294.69,982.3000000000001

%md
### Multiple Iterator Series To Iterator Series

In [0]:
@pandas_udf("double")
def price_iter_mul(cols: Iterator[Tuple[pd.Series, pd.Series]]) -> Iterator[pd.Series]:
    
    for col1, col2 in cols:
        yield col1 * col2

In [0]:
df_spark = df_spark.withColumn("iter_price_mul",price_iter_mul('price','quantity'))
display(df_spark)

order_id,customer_id,order_date,product_id,quantity,price,order_status,shipping_address,city,country,payment_method,discount,category,sales_rep,region,ship_date,delivery_days,returned,gender,total_price,iter_price,iter_price_mul
1001,C164,2025-12-04,P101,5,27.5,Pending,"418 Main St, City8",City8,Canada,Credit Card,11.81,Electronics,SR01,North,2025-12-15,4,Yes,Other,137.5,275.0,137.5
1002,C051,2025-12-23,P141,9,44.26,Returned,"211 Main St, City10",City10,Australia,Credit Card,15.18,Clothing,SR14,East,2025-12-19,3,Yes,Female,398.34,442.59999999999997,398.34
1003,C027,2025-12-03,P124,2,38.45,Cancelled,"972 Main St, City2",City5,Australia,Credit Card,14.59,Toys,SR04,West,2025-12-07,9,No,Other,76.9,384.5,76.9
1004,C159,2025-12-29,P123,10,22.45,Shipped,"150 Main St, City2",City3,India,Cash,19.7,Clothing,SR04,West,2025-12-19,8,No,Male,224.5,224.5,224.5
1005,C095,2025-12-12,P113,5,71.36,Shipped,"168 Main St, City8",City14,India,PayPal,3.27,Home,SR09,South,2025-12-22,1,Yes,Male,356.8,713.6,356.8
1006,C081,2025-12-13,P117,2,24.24,Cancelled,"270 Main St, City3",City3,Germany,Gift Card,17.69,Sports,SR15,South,2025-12-18,3,Yes,Other,48.48,242.39999999999998,48.48
1007,C144,2025-12-18,P116,10,45.12,Returned,"314 Main St, City11",City13,India,Gift Card,1.82,Electronics,SR04,South,2025-12-12,7,Yes,Female,451.2,451.2,451.2
1008,C098,2025-12-20,P129,9,28.13,Shipped,"216 Main St, City1",City18,USA,Cash,15.37,Books,SR04,East,2025-12-29,3,No,Male,253.17,281.3,253.17
1009,C185,2025-12-29,P146,5,97.29,Pending,"992 Main St, City9",City17,Australia,Cash,16.83,Toys,SR20,South,2025-12-11,6,Yes,Other,486.45000000000005,972.9000000000001,486.45000000000005
1010,C200,2025-12-30,P133,1,61.49,Returned,"731 Main St, City1",City10,UK,Cash,4.79,Clothing,SR19,North,2025-12-07,8,Yes,Other,61.49,614.9,61.49
1011,C197,2025-12-05,P108,8,94.89,Pending,"532 Main St, City8",City19,Australia,Gift Card,19.29,Toys,SR07,East,2025-12-27,6,No,Other,759.12,948.9,759.12
1012,C116,2025-12-04,P115,4,10.14,Shipped,"211 Main St, City10",City5,India,PayPal,0.14,Sports,SR02,South,2025-12-06,1,No,Male,40.56,101.4,40.56
1013,C132,2025-12-08,P117,8,24.56,Pending,"822 Main St, City15",City13,France,Gift Card,4.86,Home,SR14,South,2025-12-08,2,No,Female,196.48,245.6,196.48
1014,C109,2025-12-14,P129,1,68.63,Shipped,"311 Main St, City18",City1,Canada,Cash,16.01,Electronics,SR08,South,2025-12-14,9,No,Male,68.63,686.3,68.63
1015,C109,2025-12-06,P117,8,27.97,Shipped,"115 Main St, City18",City19,USA,Credit Card,13.04,Toys,SR01,North,2025-12-17,3,No,Female,223.76,279.7,223.76
1016,C124,2025-12-07,P125,1,19.8,Shipped,"225 Main St, City1",City5,Australia,Gift Card,5.7,Sports,SR18,West,2025-12-11,4,No,Male,19.8,198.0,19.8
1017,C015,2025-12-19,P147,9,9.84,Cancelled,"765 Main St, City4",City13,France,Gift Card,10.06,Toys,SR06,North,2026-01-03,2,Yes,Male,88.56,98.4,88.56
1018,C153,2025-12-03,P143,4,42.75,Pending,"580 Main St, City18",City20,USA,Credit Card,8.38,Toys,SR19,East,2025-12-18,4,No,Male,171.0,427.5,171.0
1019,C068,2025-12-13,P108,5,47.88,Shipped,"108 Main St, City4",City5,France,Credit Card,1.47,Clothing,SR17,East,2025-12-10,6,Yes,Male,239.4,478.8,239.4
1020,C095,2025-12-10,P110,8,84.03,Cancelled,"378 Main St, City18",City3,France,Credit Card,13.36,Toys,SR10,North,2025-12-10,5,Yes,Male,672.24,840.3,672.24
1021,C191,2025-12-18,P109,5,31.04,Pending,"452 Main St, City6",City7,India,Cash,10.11,Books,SR02,North,2025-12-29,5,Yes,Male,155.2,310.4,155.2
1022,C086,2025-12-25,P108,5,19.5,Returned,"724 Main St, City13",City10,Germany,Credit Card,2.24,Sports,SR05,North,2025-12-25,10,Yes,Female,97.5,195.0,97.5
1023,C033,2025-12-02,P119,6,90.29,Shipped,"251 Main St, City3",City12,Canada,PayPal,13.34,Books,SR18,West,2025-12-11,4,Yes,Male,541.74,902.9000000000001,541.74
1024,C106,2025-12-01,P111,6,79.1,Returned,"852 Main St, City20",City13,Australia,PayPal,5.34,Sports,SR04,West,2025-12-04,8,Yes,Male,474.59999999999997,791.0,474.59999999999997
1025,C118,2025-12-12,P119,4,25.39,Pending,"456 Main St, City1",City14,UK,Credit Card,19.34,Books,SR12,West,2026-01-05,6,Yes,Male,101.56,253.9,101.56
1026,C067,2025-12-06,P137,5,7.66,Returned,"254 Main St, City20",City3,Australia,Cash,8.73,Toys,SR04,West,2025-12-14,5,Yes,Other,38.3,76.6,38.3
1027,C112,2025-12-01,P133,9,69.93,Pending,"231 Main St, City15",City18,USA,Cash,12.46,Sports,SR04,East,2026-01-03,5,No,Female,629.3700000000001,699.3000000000001,629.3700000000001
1028,C104,2025-12-23,P118,9,16.21,Returned,"224 Main St, City11",City6,Canada,PayPal,12.31,Books,SR13,North,2025-12-21,5,Yes,Female,145.89000000000001,162.10000000000002,145.89000000000001
1029,C149,2025-12-20,P141,6,48.63,Returned,"816 Main St, City9",City7,France,Gift Card,15.87,Sports,SR06,North,2025-12-20,9,No,Male,291.78000000000003,486.3,291.78000000000003
1030,C193,2025-12-08,P143,5,25.56,Pending,"546 Main St, City6",City3,USA,PayPal,19.68,Toys,SR03,West,2025-12-28,10,Yes,Other,127.8,255.6,127.8
1031,C179,2025-12-13,P131,7,27.41,Shipped,"709 Main St, City18",City2,USA,Gift Card,4.38,Sports,SR17,West,2025-12-05,9,Yes,Male,191.87,274.1,191.87
1032,C117,2025-12-05,P129,9,98.83,Cancelled,"472 Main St, City10",City13,France,Gift Card,16.61,Toys,SR15,South,2026-01-01,8,No,Male,889.47,988.3,889.47
1033,C164,2025-12-09,P149,9,50.51,Pending,"179 Main St, City12",City7,USA,Cash,4.69,Books,SR11,North,2025-12-10,3,Yes,Female,454.59,505.09999999999997,454.59
1034,C178,2025-12-05,P145,4,10.16,Returned,"685 Main St, City10",City5,Germany,Gift Card,1.25,Home,SR13,North,2025-12-26,8,Yes,Female,40.64,101.6,40.64
1035,C077,2025-12-25,P124,7,55.66,Pending,"674 Main St, City16",City13,UK,Gift Card,9.71,Home,SR11,West,2025-12-12,8,Yes,Other,389.62,556.5999999999999,389.62
1036,C137,2025-12-01,P125,10,58.17,Shipped,"582 Main St, City15",City10,Germany,PayPal,17.34,Clothing,SR02,East,2025-12-26,6,Yes,Female,581.7,581.7,581.7
1037,C084,2025-12-11,P148,7,30.7,Returned,"399 Main St, City4",City4,Germany,Credit Card,14.98,Electronics,SR12,South,2025-12-06,1,Yes,Male,214.9,307.0,214.9
1038,C052,2025-12-27,P101,10,18.62,Pending,"481 Main St, City16",City12,USA,PayPal,9.3,Books,SR12,South,2025-12-09,3,No,Male,186.20000000000002,186.20000000000002,186.20000000000002
1039,C149,2025-12-01,P119,10,69.02,Returned,"857 Main St, City6",City18,India,Credit Card,11.84,Sports,SR08,North,2025-12-21,10,Yes,Other,690.1999999999999,690.1999999999999,690.1999999999999
1040,C011,2025-12-12,P134,7,67.5,Shipped,"992 Main St, City9",City1,UK,Credit Card,16.99,Home,SR04,West,2025-12-25,8,Yes,Female,472.5,675.0,472.5
1041,C046,2025-12-24,P133,5,63.12,Returned,"330 Main St, City5",City5,Australia,Cash,6.45,Clothing,SR03,East,2025-12-30,4,No,Other,315.59999999999997,631.1999999999999,315.59999999999997
1042,C157,2025-12-22,P124,6,6.75,Cancelled,"947 Main St, City6",City18,India,Cash,15.96,Books,SR09,East,2025-12-02,9,Yes,Male,40.5,67.5,40.5
1043,C062,2025-12-24,P126,8,57.29,Pending,"658 Main St, City4",City3,Canada,Gift Card,8.96,Electronics,SR03,East,2025-12-16,7,Yes,Female,458.32,572.9,458.32
1044,C170,2025-12-19,P123,8,57.12,Cancelled,"875 Main St, City2",City19,France,Cash,7.04,Home,SR09,East,2025-12-18,4,Yes,Other,456.96,571.1999999999999,456.96
1045,C050,2025-12-11,P107,9,95.27,Pending,"950 Main St, City7",City1,Canada,Gift Card,5.53,Toys,SR17,East,2025-12-08,4,No,Male,857.43,952.6999999999999,857.43
1046,C093,2025-12-06,P119,1,71.96,Pending,"179 Main St, City12",City4,USA,Cash,13.95,Clothing,SR16,North,2025-12-02,10,No,Female,71.96,719.5999999999999,71.96
1047,C123,2025-12-15,P121,3,96.68,Cancelled,"153 Main St, City18",City4,Australia,Credit Card,8.01,Electronics,SR19,North,2025-12-11,3,No,Male,290.04,966.8000000000001,290.04
1048,C064,2025-12-04,P135,7,62.2,Pending,"805 Main St, City4",City9,Germany,Gift Card,18.17,Books,SR19,West,2025-12-21,10,Yes,Other,435.40000000000003,622.0,435.40000000000003
1049,C190,2025-12-04,P148,4,64.04,Cancelled,"696 Main St, City5",City4,India,PayPal,3.48,Electronics,SR06,North,2025-12-28,8,No,Female,256.16,640.4000000000001,256.16
1050,C009,2025-12-08,P118,5,71.48,Returned,"132 Main St, City19",City7,India,Cash,15.76,Sports,SR19,South,2025-12-29,2,Yes,Other,357.40000000000003,714.8000000000001,357.40000000000003
1051,C039,2025-12-30,P117,3,10.85,Pending,"886 Main St, City3",City20,Canada,Cash,8.78,Home,SR10,West,2025-12-19,9,No,Female,32.55,108.5,32.55
1052,C021,2025-12-20,P102,7,74.51,Cancelled,"712 Main St, City18",City6,India,Credit Card,19.99,Sports,SR09,North,2025-12-13,8,No,Female,521.57,745.1,521.57
1053,C047,2025-12-19,P127,8,97.02,Returned,"462 Main St, City18",City15,UK,Cash,13.4,Clothing,SR11,West,2026-01-02,5,No,Other,776.16,970.1999999999999,776.16
1054,C010,2025-12-15,P105,6,28.22,Shipped,"477 Main St, City3",City1,Australia,Credit Card,13.15,Toys,SR15,West,2025-12-05,4,No,Other,169.32,282.2,169.32
1055,C194,2025-12-16,P140,8,76.95,Pending,"553 Main St, City6",City19,India,Cash,8.76,Sports,SR16,North,2025-12-03,10,Yes,Other,615.6,769.5,615.6
1056,C041,2025-12-10,P135,1,57.01,Shipped,"510 Main St, City3",City4,Germany,Credit Card,12.95,Clothing,SR16,East,2026-01-03,5,No,Female,57.01,570.1,57.01
1057,C121,2025-12-08,P129,9,17.88,Pending,"837 Main St, City1",City9,Canada,PayPal,17.28,Books,SR14,East,2026-01-03,5,Yes,Female,160.92,178.79999999999998,160.92
1058,C186,2025-12-10,P137,10,99.88,Returned,"817 Main St, City7",City20,France,Gift Card,6.9,Toys,SR18,West,2025-12-31,6,Yes,Other,998.8,998.8,998.8
1059,C062,2025-12-19,P124,4,86.17,Returned,"150 Main St, City2",City19,Canada,Gift Card,14.1,Home,SR13,South,2026-01-02,1,Yes,Other,344.68,861.7,344.68
1060,C152,2025-12-11,P106,8,13.56,Returned,"234 Main St, City17",City18,India,Gift Card,17.42,Clothing,SR03,West,2025-12-18,6,No,Other,108.48,135.6,108.48
1061,C021,2025-12-28,P121,9,40.47,Cancelled,"519 Main St, City16",City18,Australia,Gift Card,17.45,Electronics,SR20,North,2025-12-17,5,Yes,Other,364.23,404.7,364.23
1062,C024,2025-12-14,P106,2,46.58,Cancelled,"544 Main St, City17",City4,UK,Credit Card,5.87,Books,SR14,South,2025-12-17,9,No,Other,93.16,465.79999999999995,93.16
1063,C175,2025-12-26,P111,3,20.8,Returned,"907 Main St, City10",City9,India,Gift Card,18.26,Clothing,SR08,West,2025-12-18,8,No,Other,62.400000000000006,208.0,62.400000000000006
1064,C003,2025-12-29,P129,5,69.04,Pending,"132 Main St, City19",City13,UK,Cash,12.78,Home,SR09,West,2025-12-21,4,No,Female,345.20000000000005,690.4000000000001,345.20000000000005
1065,C028,2025-12-08,P124,10,38.45,Cancelled,"761 Main St, City4",City20,USA,Gift Card,5.49,Toys,SR02,West,2025-12-20,4,No,Male,384.5,384.5,384.5
1066,C163,2025-12-07,P139,5,69.06,Pending,"519 Main St, City16",City8,Canada,Credit Card,6.18,Home,SR02,East,2025-12-10,2,No,Female,345.3,690.6,345.3
1067,C192,2025-12-14,P111,4,16.68,Cancelled,"192 Main St, City6",City17,UK,PayPal,5.14,Home,SR10,East,2025-12-09,8,Yes,Male,66.72,166.8,66.72
1068,C194,2025-12-31,P114,7,96.85,Cancelled,"749 Main St, City19",City3,USA,Cash,10.73,Home,SR12,East,2025-12-26,6,Yes,Other,677.9499999999999,968.5,677.9499999999999
1069,C060,2025-12-16,P101,10,88.88,Cancelled,"378 Main St, City18",City13,Canada,Credit Card,12.71,Home,SR10,West,2025-12-09,3,Yes,Male,888.8,888.8,888.8
1070,C078,2025-12-16,P107,2,26.53,Pending,"225 Main St, City1",City19,UK,Gift Card,11.75,Sports,SR05,West,2025-12-08,8,No,Female,53.06,265.3,53.06
1071,C009,2025-12-23,P123,4,46.55,Pending,"314 Main St, City11",City7,Canada,Cash,10.89,Sports,SR12,North,2025-12-27,5,Yes,Male,186.2,465.5,186.2
1072,C117,2025-12-03,P142,4,65.59,Shipped,"262 Main St, City20",City11,India,PayPal,15.74,Clothing,SR03,South,2025-12-15,4,No,Male,262.36,655.9000000000001,262.36
1073,C153,2025-12-01,P117,3,98.79,Cancelled,"292 Main St, City17",City10,Canada,Credit Card,2.64,Books,SR08,East,2025-12-03,3,No,Male,296.37,987.9000000000001,296.37
1074,C033,2025-12-24,P126,9,14.9,Shipped,"481 Main St, City16",City20,Australia,Cash,10.26,Electronics,SR15,South,2025-12-04,9,No,Female,134.1,149.0,134.1
1075,C165,2025-12-31,P101,1,99.85,Returned,"188 Main St, City8",City7,USA,Gift Card,14.25,Home,SR03,North,2025-12-22,10,Yes,Male,99.85,998.5,99.85
1076,C033,2025-12-09,P139,10,56.63,Cancelled,"531 Main St, City6",City20,France,Cash,9.07,Toys,SR14,North,2025-12-09,9,Yes,Female,566.3000000000001,566.3000000000001,566.3000000000001
1077,C116,2025-12-29,P114,7,36.53,Returned,"456 Main St, City1",City3,Canada,Credit Card,6.25,Books,SR09,East,2025-12-11,8,Yes,Male,255.71,365.3,255.71
1078,C022,2025-12-03,P127,2,75.47,Cancelled,"173 Main St, City6",City18,USA,Cash,13.4,Home,SR12,West,2025-12-05,5,No,Female,150.94,754.7,150.94
1079,C027,2025-12-19,P132,4,18.84,Returned,"510 Main St, City3",City17,UK,Cash,2.3,Books,SR19,South,2025-12-29,9,Yes,Other,75.36,188.4,75.36
1080,C169,2025-12-27,P144,5,6.77,Cancelled,"761 Main St, City4",City5,UK,Cash,7.02,Clothing,SR05,West,2025-12-06,3,Yes,Male,33.849999999999994,67.69999999999999,33.849999999999994
1081,C192,2025-12-17,P113,7,44.29,Cancelled,"237 Main St, City4",City12,UK,Cash,15.54,Toys,SR20,North,2025-12-05,3,Yes,Other,310.03,442.9,310.03
1082,C013,2025-12-22,P105,5,46.53,Returned,"674 Main St, City16",City11,Germany,Gift Card,5.46,Toys,SR04,East,2025-12-29,2,No,Other,232.65,465.3,232.65
1083,C174,2025-12-19,P131,9,68.03,Shipped,"952 Main St, City17",City3,France,Credit Card,0.15,Books,SR07,South,2025-12-18,5,No,Male,612.27,680.3,612.27
1084,C002,2025-12-16,P147,7,20.86,Returned,"211 Main St, City4",City10,India,Cash,1.44,Sports,SR02,West,2025-12-03,8,Yes,Female,146.01999999999998,208.6,146.01999999999998
1085,C148,2025-12-14,P136,7,72.1,Returned,"605 Main St, City1",City4,Germany,Credit Card,19.32,Clothing,SR20,West,2025-12-25,2,No,Male,504.69999999999993,721.0,504.69999999999993
1086,C063,2025-12-14,P137,7,54.29,Returned,"718 Main St, City3",City19,UK,PayPal,6.66,Clothing,SR03,North,2026-01-04,9,Yes,Female,380.03,542.9,380.03
1087,C090,2025-12-24,P141,3,26.67,Pending,"821 Main St, City3",City11,India,PayPal,15.2,Sports,SR03,South,2026-01-02,8,No,Other,80.01,266.70000000000005,80.01
1088,C145,2025-12-21,P140,10,35.02,Cancelled,"817 Main St, City7",City7,USA,Gift Card,8.84,Books,SR09,North,2025-12-24,9,Yes,Female,350.20000000000005,350.20000000000005,350.20000000000005
1089,C119,2025-12-15,P102,1,39.39,Cancelled,"771 Main St, City13",City1,Australia,Credit Card,12.3,Toys,SR13,West,2025-12-04,8,Yes,Female,39.39,393.9,39.39
1090,C155,2025-12-16,P132,3,95.93,Returned,"786 Main St, City6",City7,Canada,Credit Card,10.09,Clothing,SR02,South,2025-12-30,8,Yes,Female,287.79,959.3000000000001,287.79
1091,C096,2025-12-30,P118,7,43.23,Cancelled,"909 Main St, City20",City16,USA,Cash,1.32,Electronics,SR18,West,2025-12-20,5,Yes,Female,302.60999999999996,432.29999999999995,302.60999999999996
1092,C021,2025-12-19,P142,3,92.0,Cancelled,"369 Main St, City20",City10,Canada,Gift Card,2.58,Sports,SR03,East,2025-12-26,6,Yes,Other,276.0,920.0,276.0
1093,C180,2025-12-27,P147,9,12.96,Returned,"801 Main St, City6",City5,USA,Cash,6.18,Clothing,SR11,West,2025-12-14,4,Yes,Male,116.64000000000001,129.60000000000002,116.64000000000001
1094,C020,2025-12-10,P106,9,77.99,Shipped,"696 Main St, City5",City8,Australia,PayPal,11.94,Clothing,SR06,South,2025-12-12,8,Yes,Female,701.91,779.9,701.91
1095,C094,2025-12-22,P146,4,97.07,Cancelled,"709 Main St, City18",City19,Australia,Gift Card,4.68,Clothing,SR10,West,2025-12-14,6,No,Female,388.28,970.6999999999999,388.28
1096,C197,2025-12-10,P149,7,52.27,Returned,"918 Main St, City1",City11,Australia,PayPal,17.46,Electronics,SR16,East,2025-12-08,9,Yes,Female,365.89000000000004,522.7,365.89000000000004
1097,C022,2025-12-25,P110,5,47.12,Pending,"702 Main St, City20",City6,India,Gift Card,17.69,Electronics,SR14,North,2025-12-27,9,No,Male,235.6,471.2,235.6
1098,C099,2025-12-03,P123,4,6.7,Shipped,"129 Main St, City4",City2,UK,PayPal,2.75,Books,SR16,South,2026-01-01,8,Yes,Male,26.8,67.0,26.8
1099,C005,2025-12-09,P113,3,56.68,Returned,"280 Main St, City6",City20,UK,PayPal,6.02,Electronics,SR08,West,2025-12-31,2,Yes,Female,170.04,566.8,170.04
1100,C153,2025-12-18,P101,9,59.19,Pending,"605 Main St, City1",City19,USA,Cash,4.81,Home,SR06,North,2026-01-04,6,Yes,Other,532.71,591.9,532.71
1101,C140,2025-12-17,P132,9,5.94,Returned,"150 Main St, City2",City14,Germany,Cash,5.07,Electronics,SR12,North,2025-12-24,4,Yes,Other,53.46,59.400000000000006,53.46
1102,C189,2025-12-25,P121,3,8.25,Cancelled,"227 Main St, City16",City9,Australia,Gift Card,19.62,Home,SR06,South,2025-12-06,8,Yes,Female,24.75,82.5,24.75
1103,C052,2025-12-02,P112,1,34.29,Cancelled,"375 Main St, City11",City3,Australia,Gift Card,5.07,Sports,SR07,East,2025-12-24,1,No,Female,34.29,342.9,34.29
1104,C032,2025-12-26,P123,7,89.38,Returned,"347 Main St, City12",City8,India,Gift Card,13.84,Books,SR17,East,2025-12-07,7,Yes,Female,625.66,893.8,625.66
1105,C155,2025-12-27,P111,9,32.19,Shipped,"644 Main St, City12",City9,Canada,Cash,6.13,Toys,SR14,South,2025-12-30,6,No,Male,289.71,321.9,289.71
1106,C187,2025-12-28,P122,10,99.81,Cancelled,"123 Main St, City14",City8,USA,Gift Card,7.27,Sports,SR06,North,2025-12-11,10,No,Male,998.1,998.1,998.1
1107,C033,2025-12-03,P115,6,38.76,Shipped,"972 Main St, City2",City12,Canada,Gift Card,18.98,Books,SR15,North,2025-12-10,9,No,Female,232.56,387.59999999999997,232.56
1108,C081,2025-12-21,P117,4,96.2,Shipped,"418 Main St, City8",City2,Germany,Gift Card,18.27,Electronics,SR09,East,2025-12-30,4,No,Other,384.8,962.0,384.8
1109,C126,2025-12-07,P107,3,85.86,Returned,"292 Main St, City17",City11,Germany,Credit Card,16.21,Books,SR12,North,2026-01-05,5,No,Male,257.58,858.6,257.58
1110,C183,2025-12-23,P144,3,80.18,Pending,"351 Main St, City10",City11,Australia,PayPal,4.73,Home,SR01,East,2025-12-25,8,Yes,Other,240.54000000000002,801.8000000000001,240.54000000000002
1111,C023,2025-12-03,P119,7,99.95,Returned,"170 Main St, City9",City6,Australia,Gift Card,16.47,Electronics,SR05,East,2025-12-06,8,No,Other,699.65,999.5,699.65
1112,C133,2025-12-12,P108,9,65.41,Pending,"155 Main St, City3",City11,Germany,Credit Card,16.63,Toys,SR05,East,2025-12-12,3,No,Other,588.6899999999999,654.0999999999999,588.6899999999999
1113,C058,2025-12-12,P133,5,85.2,Cancelled,"989 Main St, City8",City14,France,Cash,2.5,Books,SR20,North,2026-01-03,3,Yes,Male,426.0,852.0,426.0
1114,C169,2025-12-20,P146,10,36.4,Shipped,"544 Main St, City17",City4,USA,Cash,13.02,Toys,SR14,North,2026-01-02,9,No,Other,364.0,364.0,364.0
1115,C078,2025-12-16,P115,7,32.54,Shipped,"658 Main St, City4",City20,India,Gift Card,8.31,Home,SR07,East,2025-12-11,6,No,Other,227.78,325.4,227.78
1116,C089,2025-12-13,P108,6,53.43,Shipped,"815 Main St, City20",City1,Germany,Credit Card,5.35,Clothing,SR05,North,2025-12-05,5,No,Other,320.58,534.3,320.58
1117,C108,2025-12-08,P110,6,93.63,Cancelled,"512 Main St, City15",City5,India,Gift Card,19.92,Home,SR16,East,2026-01-02,1,Yes,Female,561.78,936.3,561.78
1118,C130,2025-12-15,P115,4,59.99,Shipped,"262 Main St, City20",City5,Germany,Gift Card,5.71,Electronics,SR04,West,2025-12-10,5,No,Female,239.96,599.9,239.96
1119,C094,2025-12-02,P125,1,58.74,Pending,"314 Main St, City11",City5,UK,Credit Card,7.73,Home,SR18,East,2025-12-09,3,Yes,Female,58.74,587.4,58.74
1120,C096,2025-12-26,P121,9,94.13,Pending,"989 Main St, City8",City15,France,Gift Card,10.0,Electronics,SR02,South,2025-12-23,8,No,Male,847.17,941.3,847.17
1121,C156,2025-12-29,P132,3,35.47,Cancelled,"918 Main St, City1",City18,France,Cash,11.87,Toys,SR17,West,2025-12-21,8,Yes,Female,106.41,354.7,106.41
1122,C085,2025-12-22,P107,7,60.03,Shipped,"979 Main St, City15",City3,UK,PayPal,14.43,Toys,SR16,South,2026-01-04,10,No,Male,420.21000000000004,600.3,420.21000000000004
1123,C175,2025-12-08,P102,10,95.02,Shipped,"512 Main St, City15",City2,Germany,Cash,8.38,Home,SR07,West,2026-01-03,10,No,Other,950.1999999999999,950.1999999999999,950.1999999999999
1124,C187,2025-12-02,P145,3,53.78,Cancelled,"696 Main St, City5",City8,France,Gift Card,6.28,Clothing,SR15,East,2026-01-05,6,No,Other,161.34,537.8,161.34

%md
### Series To Scalar

In [0]:
@pandas_udf("double")
def scalar_func(col1: pd.Series) -> float:
  return col1.mean()

In [0]:
df_spark = df_spark.groupBy("customer_id").agg(scalar_func('price').alias("mean_price"))
display(df_spark)

customer_id,mean_price
C001,54.79666666666666
C002,56.370000000000005
C003,41.7325
C004,26.42
C005,38.48
C006,41.6225
C007,43.141999999999996
C008,57.1
C009,62.125
C010,38.665
C011,59.482857142857156
C012,62.075
C013,60.54666666666666
C014,60.50666666666668
C015,17.266666666666666
C016,44.71666666666667
C017,42.42166666666667
C018,74.065
C019,76.04
C020,77.99
C021,57.73
C022,60.42999999999999
C023,74.64
C024,84.09166666666667
C025,56.50749999999999
C026,73.3
C027,31.808333333333334
C028,44.98625
C029,44.51
C030,58.02333333333333
C031,30.824
C032,67.36333333333333
C033,53.73545454545454
C034,46.26666666666667
C035,67.488
C036,44.32
C037,57.33375
C038,31.057499999999997
C039,49.0075
C040,51.422000000000004
C041,54.72666666666667
C042,53.473333333333336
C043,55.35000000000001
C044,54.576
C045,86.6
C046,79.61
C047,70.11
C048,30.271666666666665
C049,49.91
C050,76.03
C051,34.97833333333333
C052,41.48142857142857
C053,40.75333333333333
C054,42.73285714285714
C056,53.93
C057,60.28
C058,66.20142857142858
C059,35.123333333333335
C060,58.44749999999999
C061,75.115
C062,44.5825
C063,36.78
C064,49.870000000000005
C065,46.953333333333326
C066,15.94
C067,58.11333333333334
C068,60.20666666666667
C069,67.72999999999999
C070,79.13666666666667
C071,55.306
C072,53.21333333333334
C073,88.24333333333334
C074,48.934999999999995
C075,44.576666666666675
C076,73.63833333333334
C077,38.32333333333333
C078,53.068000000000005
C079,37.112500000000004
C080,46.295
C081,62.7225
C082,55.27166666666667
C083,59.28142857142858
C084,61.18
C085,47.99666666666667
C086,67.81666666666668
C087,55.331999999999994
C088,24.580000000000002
C089,53.42666666666668
C090,46.3425
C091,61.24333333333333
C092,84.69
C093,68.578
C094,61.20857142857142
C095,64.77099999999999
C096,59.94624999999999
C097,26.80666666666667
C098,57.218
C099,47.05875
C100,57.468333333333334
C101,77.16
C102,80.55
C103,87.82999999999998
C104,56.25333333333333
C105,51.165000000000006
C106,53.58857142857142
C107,51.669999999999995
C108,58.58
C109,47.16444444444445
C110,60.633333333333326
C111,32.75333333333334
C112,47.88833333333334
C113,48.795
C114,63.115
C115,45.06142857142857
C116,25.197499999999998
C117,60.57
C118,63.186
C119,47.827999999999996
C120,50.64
C121,53.20142857142857
C122,57.394285714285715
C123,55.56666666666667
C124,40.75
C125,33.11
C126,41.84400000000001
C127,55.497499999999995
C128,51.56
C129,33.02333333333333
C130,41.14333333333334
C131,26.205
C132,27.703333333333333
C133,56.948
C134,71.05
C135,44.13
C136,28.805
C137,43.737500000000004
C138,52.913333333333334
C139,61.13125
C140,55.303999999999995
C141,56.54666666666666
C142,23.74
C143,66.0175
C144,31.965714285714288
C145,60.989999999999995
C146,35.7125
C147,46.743
C148,46.60142857142857
C149,65.4725
C151,35.913333333333334
C152,50.98
C153,48.658750000000005
C154,47.11666666666667
C155,67.91400000000002
C156,65.12888888888888
C157,60.34
C158,31.248
C159,37.0
C160,28.439999999999998
C161,56.475
C162,37.76
C163,49.092
C164,41.48666666666666
C165,69.83250000000001
C166,42.86666666666667
C167,78.055
C168,51.61
C169,55.3925
C170,53.92666666666667
C172,54.932500000000005
C173,68.31333333333333
C174,65.31
C175,60.884
C176,62.38777777777778
C177,68.86
C178,25.51
C179,38.98125
C180,45.995000000000005
C181,38.82571428571429
C182,42.586
C183,60.762499999999996
C184,66.94
C185,60.55833333333334
C186,54.01642857142857
C187,54.226
C188,57.378
C189,40.129999999999995
C190,48.856666666666676
C191,41.324444444444445
C192,30.398571428571422
C193,53.36166666666667
C194,59.71
C195,39.18714285714285
C196,68.9
C197,64.20428571428572
C198,50.435
C199,74.84714285714286
C200,78.18

### Using It With Spark SQL

In [0]:
df_spark = spark.read.format("csv")\
                .option("header","true")\
                .option("inferSchema","true")\
                .load("/Volumes/sparkcatalog/raw/source/raw_orders/orders.csv")

In [0]:
df_spark.createOrReplaceTempView("df_spark")

In [0]:
spark.udf.register("price_iter_mul_udf", price_iter_mul)

In [0]:
display(spark.sql("""
          SELECT 
            *,
            price_iter_mul_udf(price, quantity) as iter_price_mul
        FROM 
            df_spark"""))

order_id,customer_id,order_date,product_id,quantity,price,order_status,shipping_address,city,country,payment_method,discount,category,sales_rep,region,ship_date,delivery_days,returned,gender,iter_price_mul
1001,C164,2025-12-04,P101,5,27.5,Pending,"418 Main St, City8",City8,Canada,Credit Card,11.81,Electronics,SR01,North,2025-12-15,4,Yes,Other,137.5
1002,C051,2025-12-23,P141,9,44.26,Returned,"211 Main St, City10",City10,Australia,Credit Card,15.18,Clothing,SR14,East,2025-12-19,3,Yes,Female,398.34
1003,C027,2025-12-03,P124,2,38.45,Cancelled,"972 Main St, City2",City5,Australia,Credit Card,14.59,Toys,SR04,West,2025-12-07,9,No,Other,76.9
1004,C159,2025-12-29,P123,10,22.45,Shipped,"150 Main St, City2",City3,India,Cash,19.7,Clothing,SR04,West,2025-12-19,8,No,Male,224.5
1005,C095,2025-12-12,P113,5,71.36,Shipped,"168 Main St, City8",City14,India,PayPal,3.27,Home,SR09,South,2025-12-22,1,Yes,Male,356.8
1006,C081,2025-12-13,P117,2,24.24,Cancelled,"270 Main St, City3",City3,Germany,Gift Card,17.69,Sports,SR15,South,2025-12-18,3,Yes,Other,48.48
1007,C144,2025-12-18,P116,10,45.12,Returned,"314 Main St, City11",City13,India,Gift Card,1.82,Electronics,SR04,South,2025-12-12,7,Yes,Female,451.2
1008,C098,2025-12-20,P129,9,28.13,Shipped,"216 Main St, City1",City18,USA,Cash,15.37,Books,SR04,East,2025-12-29,3,No,Male,253.17
1009,C185,2025-12-29,P146,5,97.29,Pending,"992 Main St, City9",City17,Australia,Cash,16.83,Toys,SR20,South,2025-12-11,6,Yes,Other,486.45000000000005
1010,C200,2025-12-30,P133,1,61.49,Returned,"731 Main St, City1",City10,UK,Cash,4.79,Clothing,SR19,North,2025-12-07,8,Yes,Other,61.49
1011,C197,2025-12-05,P108,8,94.89,Pending,"532 Main St, City8",City19,Australia,Gift Card,19.29,Toys,SR07,East,2025-12-27,6,No,Other,759.12
1012,C116,2025-12-04,P115,4,10.14,Shipped,"211 Main St, City10",City5,India,PayPal,0.14,Sports,SR02,South,2025-12-06,1,No,Male,40.56
1013,C132,2025-12-08,P117,8,24.56,Pending,"822 Main St, City15",City13,France,Gift Card,4.86,Home,SR14,South,2025-12-08,2,No,Female,196.48
1014,C109,2025-12-14,P129,1,68.63,Shipped,"311 Main St, City18",City1,Canada,Cash,16.01,Electronics,SR08,South,2025-12-14,9,No,Male,68.63
1015,C109,2025-12-06,P117,8,27.97,Shipped,"115 Main St, City18",City19,USA,Credit Card,13.04,Toys,SR01,North,2025-12-17,3,No,Female,223.76
1016,C124,2025-12-07,P125,1,19.8,Shipped,"225 Main St, City1",City5,Australia,Gift Card,5.7,Sports,SR18,West,2025-12-11,4,No,Male,19.8
1017,C015,2025-12-19,P147,9,9.84,Cancelled,"765 Main St, City4",City13,France,Gift Card,10.06,Toys,SR06,North,2026-01-03,2,Yes,Male,88.56
1018,C153,2025-12-03,P143,4,42.75,Pending,"580 Main St, City18",City20,USA,Credit Card,8.38,Toys,SR19,East,2025-12-18,4,No,Male,171.0
1019,C068,2025-12-13,P108,5,47.88,Shipped,"108 Main St, City4",City5,France,Credit Card,1.47,Clothing,SR17,East,2025-12-10,6,Yes,Male,239.4
1020,C095,2025-12-10,P110,8,84.03,Cancelled,"378 Main St, City18",City3,France,Credit Card,13.36,Toys,SR10,North,2025-12-10,5,Yes,Male,672.24
1021,C191,2025-12-18,P109,5,31.04,Pending,"452 Main St, City6",City7,India,Cash,10.11,Books,SR02,North,2025-12-29,5,Yes,Male,155.2
1022,C086,2025-12-25,P108,5,19.5,Returned,"724 Main St, City13",City10,Germany,Credit Card,2.24,Sports,SR05,North,2025-12-25,10,Yes,Female,97.5
1023,C033,2025-12-02,P119,6,90.29,Shipped,"251 Main St, City3",City12,Canada,PayPal,13.34,Books,SR18,West,2025-12-11,4,Yes,Male,541.74
1024,C106,2025-12-01,P111,6,79.1,Returned,"852 Main St, City20",City13,Australia,PayPal,5.34,Sports,SR04,West,2025-12-04,8,Yes,Male,474.59999999999997
1025,C118,2025-12-12,P119,4,25.39,Pending,"456 Main St, City1",City14,UK,Credit Card,19.34,Books,SR12,West,2026-01-05,6,Yes,Male,101.56
1026,C067,2025-12-06,P137,5,7.66,Returned,"254 Main St, City20",City3,Australia,Cash,8.73,Toys,SR04,West,2025-12-14,5,Yes,Other,38.3
1027,C112,2025-12-01,P133,9,69.93,Pending,"231 Main St, City15",City18,USA,Cash,12.46,Sports,SR04,East,2026-01-03,5,No,Female,629.3700000000001
1028,C104,2025-12-23,P118,9,16.21,Returned,"224 Main St, City11",City6,Canada,PayPal,12.31,Books,SR13,North,2025-12-21,5,Yes,Female,145.89000000000001
1029,C149,2025-12-20,P141,6,48.63,Returned,"816 Main St, City9",City7,France,Gift Card,15.87,Sports,SR06,North,2025-12-20,9,No,Male,291.78000000000003
1030,C193,2025-12-08,P143,5,25.56,Pending,"546 Main St, City6",City3,USA,PayPal,19.68,Toys,SR03,West,2025-12-28,10,Yes,Other,127.8
1031,C179,2025-12-13,P131,7,27.41,Shipped,"709 Main St, City18",City2,USA,Gift Card,4.38,Sports,SR17,West,2025-12-05,9,Yes,Male,191.87
1032,C117,2025-12-05,P129,9,98.83,Cancelled,"472 Main St, City10",City13,France,Gift Card,16.61,Toys,SR15,South,2026-01-01,8,No,Male,889.47
1033,C164,2025-12-09,P149,9,50.51,Pending,"179 Main St, City12",City7,USA,Cash,4.69,Books,SR11,North,2025-12-10,3,Yes,Female,454.59
1034,C178,2025-12-05,P145,4,10.16,Returned,"685 Main St, City10",City5,Germany,Gift Card,1.25,Home,SR13,North,2025-12-26,8,Yes,Female,40.64
1035,C077,2025-12-25,P124,7,55.66,Pending,"674 Main St, City16",City13,UK,Gift Card,9.71,Home,SR11,West,2025-12-12,8,Yes,Other,389.62
1036,C137,2025-12-01,P125,10,58.17,Shipped,"582 Main St, City15",City10,Germany,PayPal,17.34,Clothing,SR02,East,2025-12-26,6,Yes,Female,581.7
1037,C084,2025-12-11,P148,7,30.7,Returned,"399 Main St, City4",City4,Germany,Credit Card,14.98,Electronics,SR12,South,2025-12-06,1,Yes,Male,214.9
1038,C052,2025-12-27,P101,10,18.62,Pending,"481 Main St, City16",City12,USA,PayPal,9.3,Books,SR12,South,2025-12-09,3,No,Male,186.20000000000002
1039,C149,2025-12-01,P119,10,69.02,Returned,"857 Main St, City6",City18,India,Credit Card,11.84,Sports,SR08,North,2025-12-21,10,Yes,Other,690.1999999999999
1040,C011,2025-12-12,P134,7,67.5,Shipped,"992 Main St, City9",City1,UK,Credit Card,16.99,Home,SR04,West,2025-12-25,8,Yes,Female,472.5
1041,C046,2025-12-24,P133,5,63.12,Returned,"330 Main St, City5",City5,Australia,Cash,6.45,Clothing,SR03,East,2025-12-30,4,No,Other,315.59999999999997
1042,C157,2025-12-22,P124,6,6.75,Cancelled,"947 Main St, City6",City18,India,Cash,15.96,Books,SR09,East,2025-12-02,9,Yes,Male,40.5
1043,C062,2025-12-24,P126,8,57.29,Pending,"658 Main St, City4",City3,Canada,Gift Card,8.96,Electronics,SR03,East,2025-12-16,7,Yes,Female,458.32
1044,C170,2025-12-19,P123,8,57.12,Cancelled,"875 Main St, City2",City19,France,Cash,7.04,Home,SR09,East,2025-12-18,4,Yes,Other,456.96
1045,C050,2025-12-11,P107,9,95.27,Pending,"950 Main St, City7",City1,Canada,Gift Card,5.53,Toys,SR17,East,2025-12-08,4,No,Male,857.43
1046,C093,2025-12-06,P119,1,71.96,Pending,"179 Main St, City12",City4,USA,Cash,13.95,Clothing,SR16,North,2025-12-02,10,No,Female,71.96
1047,C123,2025-12-15,P121,3,96.68,Cancelled,"153 Main St, City18",City4,Australia,Credit Card,8.01,Electronics,SR19,North,2025-12-11,3,No,Male,290.04
1048,C064,2025-12-04,P135,7,62.2,Pending,"805 Main St, City4",City9,Germany,Gift Card,18.17,Books,SR19,West,2025-12-21,10,Yes,Other,435.40000000000003
1049,C190,2025-12-04,P148,4,64.04,Cancelled,"696 Main St, City5",City4,India,PayPal,3.48,Electronics,SR06,North,2025-12-28,8,No,Female,256.16
1050,C009,2025-12-08,P118,5,71.48,Returned,"132 Main St, City19",City7,India,Cash,15.76,Sports,SR19,South,2025-12-29,2,Yes,Other,357.40000000000003
1051,C039,2025-12-30,P117,3,10.85,Pending,"886 Main St, City3",City20,Canada,Cash,8.78,Home,SR10,West,2025-12-19,9,No,Female,32.55
1052,C021,2025-12-20,P102,7,74.51,Cancelled,"712 Main St, City18",City6,India,Credit Card,19.99,Sports,SR09,North,2025-12-13,8,No,Female,521.57
1053,C047,2025-12-19,P127,8,97.02,Returned,"462 Main St, City18",City15,UK,Cash,13.4,Clothing,SR11,West,2026-01-02,5,No,Other,776.16
1054,C010,2025-12-15,P105,6,28.22,Shipped,"477 Main St, City3",City1,Australia,Credit Card,13.15,Toys,SR15,West,2025-12-05,4,No,Other,169.32
1055,C194,2025-12-16,P140,8,76.95,Pending,"553 Main St, City6",City19,India,Cash,8.76,Sports,SR16,North,2025-12-03,10,Yes,Other,615.6
1056,C041,2025-12-10,P135,1,57.01,Shipped,"510 Main St, City3",City4,Germany,Credit Card,12.95,Clothing,SR16,East,2026-01-03,5,No,Female,57.01
1057,C121,2025-12-08,P129,9,17.88,Pending,"837 Main St, City1",City9,Canada,PayPal,17.28,Books,SR14,East,2026-01-03,5,Yes,Female,160.92
1058,C186,2025-12-10,P137,10,99.88,Returned,"817 Main St, City7",City20,France,Gift Card,6.9,Toys,SR18,West,2025-12-31,6,Yes,Other,998.8
1059,C062,2025-12-19,P124,4,86.17,Returned,"150 Main St, City2",City19,Canada,Gift Card,14.1,Home,SR13,South,2026-01-02,1,Yes,Other,344.68
1060,C152,2025-12-11,P106,8,13.56,Returned,"234 Main St, City17",City18,India,Gift Card,17.42,Clothing,SR03,West,2025-12-18,6,No,Other,108.48
1061,C021,2025-12-28,P121,9,40.47,Cancelled,"519 Main St, City16",City18,Australia,Gift Card,17.45,Electronics,SR20,North,2025-12-17,5,Yes,Other,364.23
1062,C024,2025-12-14,P106,2,46.58,Cancelled,"544 Main St, City17",City4,UK,Credit Card,5.87,Books,SR14,South,2025-12-17,9,No,Other,93.16
1063,C175,2025-12-26,P111,3,20.8,Returned,"907 Main St, City10",City9,India,Gift Card,18.26,Clothing,SR08,West,2025-12-18,8,No,Other,62.400000000000006
1064,C003,2025-12-29,P129,5,69.04,Pending,"132 Main St, City19",City13,UK,Cash,12.78,Home,SR09,West,2025-12-21,4,No,Female,345.20000000000005
1065,C028,2025-12-08,P124,10,38.45,Cancelled,"761 Main St, City4",City20,USA,Gift Card,5.49,Toys,SR02,West,2025-12-20,4,No,Male,384.5
1066,C163,2025-12-07,P139,5,69.06,Pending,"519 Main St, City16",City8,Canada,Credit Card,6.18,Home,SR02,East,2025-12-10,2,No,Female,345.3
1067,C192,2025-12-14,P111,4,16.68,Cancelled,"192 Main St, City6",City17,UK,PayPal,5.14,Home,SR10,East,2025-12-09,8,Yes,Male,66.72
1068,C194,2025-12-31,P114,7,96.85,Cancelled,"749 Main St, City19",City3,USA,Cash,10.73,Home,SR12,East,2025-12-26,6,Yes,Other,677.9499999999999
1069,C060,2025-12-16,P101,10,88.88,Cancelled,"378 Main St, City18",City13,Canada,Credit Card,12.71,Home,SR10,West,2025-12-09,3,Yes,Male,888.8
1070,C078,2025-12-16,P107,2,26.53,Pending,"225 Main St, City1",City19,UK,Gift Card,11.75,Sports,SR05,West,2025-12-08,8,No,Female,53.06
1071,C009,2025-12-23,P123,4,46.55,Pending,"314 Main St, City11",City7,Canada,Cash,10.89,Sports,SR12,North,2025-12-27,5,Yes,Male,186.2
1072,C117,2025-12-03,P142,4,65.59,Shipped,"262 Main St, City20",City11,India,PayPal,15.74,Clothing,SR03,South,2025-12-15,4,No,Male,262.36
1073,C153,2025-12-01,P117,3,98.79,Cancelled,"292 Main St, City17",City10,Canada,Credit Card,2.64,Books,SR08,East,2025-12-03,3,No,Male,296.37
1074,C033,2025-12-24,P126,9,14.9,Shipped,"481 Main St, City16",City20,Australia,Cash,10.26,Electronics,SR15,South,2025-12-04,9,No,Female,134.1
1075,C165,2025-12-31,P101,1,99.85,Returned,"188 Main St, City8",City7,USA,Gift Card,14.25,Home,SR03,North,2025-12-22,10,Yes,Male,99.85
1076,C033,2025-12-09,P139,10,56.63,Cancelled,"531 Main St, City6",City20,France,Cash,9.07,Toys,SR14,North,2025-12-09,9,Yes,Female,566.3000000000001
1077,C116,2025-12-29,P114,7,36.53,Returned,"456 Main St, City1",City3,Canada,Credit Card,6.25,Books,SR09,East,2025-12-11,8,Yes,Male,255.71
1078,C022,2025-12-03,P127,2,75.47,Cancelled,"173 Main St, City6",City18,USA,Cash,13.4,Home,SR12,West,2025-12-05,5,No,Female,150.94
1079,C027,2025-12-19,P132,4,18.84,Returned,"510 Main St, City3",City17,UK,Cash,2.3,Books,SR19,South,2025-12-29,9,Yes,Other,75.36
1080,C169,2025-12-27,P144,5,6.77,Cancelled,"761 Main St, City4",City5,UK,Cash,7.02,Clothing,SR05,West,2025-12-06,3,Yes,Male,33.849999999999994
1081,C192,2025-12-17,P113,7,44.29,Cancelled,"237 Main St, City4",City12,UK,Cash,15.54,Toys,SR20,North,2025-12-05,3,Yes,Other,310.03
1082,C013,2025-12-22,P105,5,46.53,Returned,"674 Main St, City16",City11,Germany,Gift Card,5.46,Toys,SR04,East,2025-12-29,2,No,Other,232.65
1083,C174,2025-12-19,P131,9,68.03,Shipped,"952 Main St, City17",City3,France,Credit Card,0.15,Books,SR07,South,2025-12-18,5,No,Male,612.27
1084,C002,2025-12-16,P147,7,20.86,Returned,"211 Main St, City4",City10,India,Cash,1.44,Sports,SR02,West,2025-12-03,8,Yes,Female,146.01999999999998
1085,C148,2025-12-14,P136,7,72.1,Returned,"605 Main St, City1",City4,Germany,Credit Card,19.32,Clothing,SR20,West,2025-12-25,2,No,Male,504.69999999999993
1086,C063,2025-12-14,P137,7,54.29,Returned,"718 Main St, City3",City19,UK,PayPal,6.66,Clothing,SR03,North,2026-01-04,9,Yes,Female,380.03
1087,C090,2025-12-24,P141,3,26.67,Pending,"821 Main St, City3",City11,India,PayPal,15.2,Sports,SR03,South,2026-01-02,8,No,Other,80.01
1088,C145,2025-12-21,P140,10,35.02,Cancelled,"817 Main St, City7",City7,USA,Gift Card,8.84,Books,SR09,North,2025-12-24,9,Yes,Female,350.20000000000005
1089,C119,2025-12-15,P102,1,39.39,Cancelled,"771 Main St, City13",City1,Australia,Credit Card,12.3,Toys,SR13,West,2025-12-04,8,Yes,Female,39.39
1090,C155,2025-12-16,P132,3,95.93,Returned,"786 Main St, City6",City7,Canada,Credit Card,10.09,Clothing,SR02,South,2025-12-30,8,Yes,Female,287.79
1091,C096,2025-12-30,P118,7,43.23,Cancelled,"909 Main St, City20",City16,USA,Cash,1.32,Electronics,SR18,West,2025-12-20,5,Yes,Female,302.60999999999996
1092,C021,2025-12-19,P142,3,92.0,Cancelled,"369 Main St, City20",City10,Canada,Gift Card,2.58,Sports,SR03,East,2025-12-26,6,Yes,Other,276.0
1093,C180,2025-12-27,P147,9,12.96,Returned,"801 Main St, City6",City5,USA,Cash,6.18,Clothing,SR11,West,2025-12-14,4,Yes,Male,116.64000000000001
1094,C020,2025-12-10,P106,9,77.99,Shipped,"696 Main St, City5",City8,Australia,PayPal,11.94,Clothing,SR06,South,2025-12-12,8,Yes,Female,701.91
1095,C094,2025-12-22,P146,4,97.07,Cancelled,"709 Main St, City18",City19,Australia,Gift Card,4.68,Clothing,SR10,West,2025-12-14,6,No,Female,388.28
1096,C197,2025-12-10,P149,7,52.27,Returned,"918 Main St, City1",City11,Australia,PayPal,17.46,Electronics,SR16,East,2025-12-08,9,Yes,Female,365.89000000000004
1097,C022,2025-12-25,P110,5,47.12,Pending,"702 Main St, City20",City6,India,Gift Card,17.69,Electronics,SR14,North,2025-12-27,9,No,Male,235.6
1098,C099,2025-12-03,P123,4,6.7,Shipped,"129 Main St, City4",City2,UK,PayPal,2.75,Books,SR16,South,2026-01-01,8,Yes,Male,26.8
1099,C005,2025-12-09,P113,3,56.68,Returned,"280 Main St, City6",City20,UK,PayPal,6.02,Electronics,SR08,West,2025-12-31,2,Yes,Female,170.04
1100,C153,2025-12-18,P101,9,59.19,Pending,"605 Main St, City1",City19,USA,Cash,4.81,Home,SR06,North,2026-01-04,6,Yes,Other,532.71
1101,C140,2025-12-17,P132,9,5.94,Returned,"150 Main St, City2",City14,Germany,Cash,5.07,Electronics,SR12,North,2025-12-24,4,Yes,Other,53.46
1102,C189,2025-12-25,P121,3,8.25,Cancelled,"227 Main St, City16",City9,Australia,Gift Card,19.62,Home,SR06,South,2025-12-06,8,Yes,Female,24.75
1103,C052,2025-12-02,P112,1,34.29,Cancelled,"375 Main St, City11",City3,Australia,Gift Card,5.07,Sports,SR07,East,2025-12-24,1,No,Female,34.29
1104,C032,2025-12-26,P123,7,89.38,Returned,"347 Main St, City12",City8,India,Gift Card,13.84,Books,SR17,East,2025-12-07,7,Yes,Female,625.66
1105,C155,2025-12-27,P111,9,32.19,Shipped,"644 Main St, City12",City9,Canada,Cash,6.13,Toys,SR14,South,2025-12-30,6,No,Male,289.71
1106,C187,2025-12-28,P122,10,99.81,Cancelled,"123 Main St, City14",City8,USA,Gift Card,7.27,Sports,SR06,North,2025-12-11,10,No,Male,998.1
1107,C033,2025-12-03,P115,6,38.76,Shipped,"972 Main St, City2",City12,Canada,Gift Card,18.98,Books,SR15,North,2025-12-10,9,No,Female,232.56
1108,C081,2025-12-21,P117,4,96.2,Shipped,"418 Main St, City8",City2,Germany,Gift Card,18.27,Electronics,SR09,East,2025-12-30,4,No,Other,384.8
1109,C126,2025-12-07,P107,3,85.86,Returned,"292 Main St, City17",City11,Germany,Credit Card,16.21,Books,SR12,North,2026-01-05,5,No,Male,257.58
1110,C183,2025-12-23,P144,3,80.18,Pending,"351 Main St, City10",City11,Australia,PayPal,4.73,Home,SR01,East,2025-12-25,8,Yes,Other,240.54000000000002
1111,C023,2025-12-03,P119,7,99.95,Returned,"170 Main St, City9",City6,Australia,Gift Card,16.47,Electronics,SR05,East,2025-12-06,8,No,Other,699.65
1112,C133,2025-12-12,P108,9,65.41,Pending,"155 Main St, City3",City11,Germany,Credit Card,16.63,Toys,SR05,East,2025-12-12,3,No,Other,588.6899999999999
1113,C058,2025-12-12,P133,5,85.2,Cancelled,"989 Main St, City8",City14,France,Cash,2.5,Books,SR20,North,2026-01-03,3,Yes,Male,426.0
1114,C169,2025-12-20,P146,10,36.4,Shipped,"544 Main St, City17",City4,USA,Cash,13.02,Toys,SR14,North,2026-01-02,9,No,Other,364.0
1115,C078,2025-12-16,P115,7,32.54,Shipped,"658 Main St, City4",City20,India,Gift Card,8.31,Home,SR07,East,2025-12-11,6,No,Other,227.78
1116,C089,2025-12-13,P108,6,53.43,Shipped,"815 Main St, City20",City1,Germany,Credit Card,5.35,Clothing,SR05,North,2025-12-05,5,No,Other,320.58
1117,C108,2025-12-08,P110,6,93.63,Cancelled,"512 Main St, City15",City5,India,Gift Card,19.92,Home,SR16,East,2026-01-02,1,Yes,Female,561.78
1118,C130,2025-12-15,P115,4,59.99,Shipped,"262 Main St, City20",City5,Germany,Gift Card,5.71,Electronics,SR04,West,2025-12-10,5,No,Female,239.96
1119,C094,2025-12-02,P125,1,58.74,Pending,"314 Main St, City11",City5,UK,Credit Card,7.73,Home,SR18,East,2025-12-09,3,Yes,Female,58.74
1120,C096,2025-12-26,P121,9,94.13,Pending,"989 Main St, City8",City15,France,Gift Card,10.0,Electronics,SR02,South,2025-12-23,8,No,Male,847.17
1121,C156,2025-12-29,P132,3,35.47,Cancelled,"918 Main St, City1",City18,France,Cash,11.87,Toys,SR17,West,2025-12-21,8,Yes,Female,106.41
1122,C085,2025-12-22,P107,7,60.03,Shipped,"979 Main St, City15",City3,UK,PayPal,14.43,Toys,SR16,South,2026-01-04,10,No,Male,420.21000000000004
1123,C175,2025-12-08,P102,10,95.02,Shipped,"512 Main St, City15",City2,Germany,Cash,8.38,Home,SR07,West,2026-01-03,10,No,Other,950.1999999999999
1124,C187,2025-12-02,P145,3,53.78,Cancelled,"696 Main St, City5",City8,France,Gift Card,6.28,Clothing,SR15,East,2026-01-05,6,No,Other,161.34
1125,C124,2025-12-07,P115,5,57.57,Pending,"372 Main St, City15",City2,UK,PayPal,13.8,Home,SR11,West,2025-12-24,9,No,Female,287.85
1126,C032,2025-12-19,P143,9,40.44,Returned,"254 Main St, City20",City2,Australia,PayPal,5.81,Books,SR03,East,2025-12-30,5,No,Male,363.96
1127,C052,2025-12-27,P134,5,93.56,Cancelled,"754 Main St, City5",City17,France,PayPal,4.85,Sports,SR17,South,2025-12-16,1,Yes,Female,467.8
1128,C085,2025-12-23,P130,2,69.38,Pending,"713 Main St, City5",City19,India,Gift Card,13.06,Home,SR16,South,2025-12-20,6,No,Other,138.76
1129,C016,2025-12-30,P149,2,66.61,Pending,"211 Main St, City4",City3,Canada,Credit Card,18.26,Clothing,SR14,South,2025-12-04,7,No,Male,133.22
1130,C192,2025-12-31,P118,1,4.88,Shipped,"512 Main St, City20",City5,Germany,Gift Card,17.79,Clothing,SR17,West,2025-12-19,4,Yes,Female,4.88
1131,C042,2025-12-24,P129,5,72.98,Shipped,"418 Main St, City8",City8,Australia,Cash,11.36,Clothing,SR06,West,2025-12-29,9,No,Male,364.90000000000003
1132,C103,2025-12-22,P106,3,98.23,Returned,"192 Main St, City5",City5,USA,Cash,7.67,Home,SR09,East,2025-12-21,10,Yes,Female,294.69
1133,C168,2025-12-12,P144,4,9.95,Shipped,"330 Main St, City5",City20,India,Gift Card,13.72,Sports,SR10,North,2025-12-20,6,Yes,Male,39.8
1134,C035,2025-12-16,P109,8,75.77,Cancelled,"190 Main St, City20",City20,France,Gift Card,15.15,Sports,SR07,South,2025-12-07,9,No,Other,606.16
1135,C181,2025-12-12,P104,10,14.76,Pending,"765 Main St, City1",City6,India,PayPal,6.56,Toys,SR15,North,2025-12-15,10,No,Male,147.6
1136,C131,2025-12-15,P103,8,16.66,Returned,"800 Main St, City4",City6,USA,Gift Card,13.46,Books,SR01,West,2025-12-18,1,Yes,Other,133.28
1137,C019,2025-12-02,P127,6,71.23,Shipped,"393 Main St, City15",City9,USA,Cash,8.18,Clothing,SR14,East,2025-12-26,8,No,Female,427.38
1138,C021,2025-12-22,P142,9,16.76,Cancelled,"938 Main St, City19",City3,France,Gift Card,10.58,Sports,SR08,North,2025-12-03,5,No,Other,150.84
1139,C185,2025-12-18,P127,9,40.4,Pending,"569 Main St, City3",City5,UK,PayPal,5.51,Sports,SR04,North,2025-12-28,10,Yes,Male,363.59999999999997
1140,C053,2025-12-03,P106,10,7.21,Shipped,"364 Main St, City11",City3,USA,Gift Card,8.78,Toys,SR07,North,2025-12-10,9,No,Male,72.1
1141,C188,2025-12-19,P120,10,61.39,Cancelled,"885 Main St, City5",City6,India,PayPal,8.27,Books,SR02,South,2025-12-29,9,No,Male,613.9